// Copyright (c) Obelisk Labs, Inc.
// SPDX-License-Identifier: Apache-2.0

/* Autogenerated file. Do not edit manually. */

module counter::error {
    #[error]
    const EInvalidIncrement: vector<u8> = b"Number can't be incremented, must be more than 0";
    public fun invalid_increment(condition: bool) { assert!(condition, EInvalidIncrement) }
}
