// Copyright (c) Obelisk Labs, Inc.
// SPDX-License-Identifier: Apache-2.0

/* Autogenerated file. Do not edit manually. */

module harvest::crop_type {
    use sui::bcs::{BCS, to_bytes, peel_enum_tag};

    public enum CropType has copy, drop, store {
        Carrot,Corn,None,Pumpkin,Wheat
    }

    public fun new_carrot(): CropType {
        CropType::Carrot
    }

    public fun new_corn(): CropType {
        CropType::Corn
    }

    public fun new_none(): CropType {
        CropType::None
    }

    public fun new_pumpkin(): CropType {
        CropType::Pumpkin
    }

    public fun new_wheat(): CropType {
        CropType::Wheat
    }

    public fun encode(self: CropType): vector<u8> {
        to_bytes(&self)
    }

    public fun decode(bytes: &mut BCS): CropType {
        match(peel_enum_tag(bytes)) {
            0 => CropType::Carrot,
            1 => CropType::Corn,
            2 => CropType::None,
            3 => CropType::Pumpkin,
            4 => CropType::Wheat,
            _ => abort,
        }
    }
}