// Copyright (c) Obelisk Labs, Inc.
// SPDX-License-Identifier: Apache-2.0

/* Autogenerated file. Do not edit manually. */

module harvest::egg_type {
    use sui::bcs::{BCS, to_bytes, peel_enum_tag};

    public enum EggType has copy, drop, store {
        Common,None,Rare,Seasonal
    }

    public fun new_common(): EggType {
        EggType::Common
    }

    public fun new_none(): EggType {
        EggType::None
    }

    public fun new_rare(): EggType {
        EggType::Rare
    }

    public fun new_seasonal(): EggType {
        EggType::Seasonal
    }

    public fun encode(self: EggType): vector<u8> {
        to_bytes(&self)
    }

    public fun decode(bytes: &mut BCS): EggType {
        match(peel_enum_tag(bytes)) {
            0 => EggType::Common,
            1 => EggType::None,
            2 => EggType::Rare,
            3 => EggType::Seasonal,
            _ => abort,
        }
    }
}