// Copyright (c) Obelisk Labs, Inc.
// SPDX-License-Identifier: Apache-2.0

/* Autogenerated file. Do not edit manually. */

module harvest::pet_rarity {
    use sui::bcs::{BCS, to_bytes, peel_enum_tag};

    public enum PetRarity has copy, drop, store {
        Common,Rare,Uncommon
    }

    public fun new_common(): PetRarity {
        PetRarity::Common
    }

    public fun new_rare(): PetRarity {
        PetRarity::Rare
    }

    public fun new_uncommon(): PetRarity {
        PetRarity::Uncommon
    }

    public fun encode(self: PetRarity): vector<u8> {
        to_bytes(&self)
    }

    public fun decode(bytes: &mut BCS): PetRarity {
        match(peel_enum_tag(bytes)) {
            0 => PetRarity::Common,
            1 => PetRarity::Rare,
            2 => PetRarity::Uncommon,
            _ => abort,
        }
    }
}