// Copyright (c) Obelisk Labs, Inc.
// SPDX-License-Identifier: Apache-2.0

/* Autogenerated file. Do not edit manually. */

module harvest::pet_species {
    use sui::bcs::{BCS, to_bytes, peel_enum_tag};

    public enum PetSpecies has copy, drop, store {
        Bunny,Chick,Deer,Dragon,Fox,None
    }

    public fun new_bunny(): PetSpecies {
        PetSpecies::Bunny
    }

    public fun new_chick(): PetSpecies {
        PetSpecies::Chick
    }

    public fun new_deer(): PetSpecies {
        PetSpecies::Deer
    }

    public fun new_dragon(): PetSpecies {
        PetSpecies::Dragon
    }

    public fun new_fox(): PetSpecies {
        PetSpecies::Fox
    }

    public fun new_none(): PetSpecies {
        PetSpecies::None
    }

    public fun encode(self: PetSpecies): vector<u8> {
        to_bytes(&self)
    }

    public fun decode(bytes: &mut BCS): PetSpecies {
        match(peel_enum_tag(bytes)) {
            0 => PetSpecies::Bunny,
            1 => PetSpecies::Chick,
            2 => PetSpecies::Deer,
            3 => PetSpecies::Dragon,
            4 => PetSpecies::Fox,
            5 => PetSpecies::None,
            _ => abort,
        }
    }
}