// Copyright (c) Obelisk Labs, Inc.
// SPDX-License-Identifier: Apache-2.0

/* Autogenerated file. Do not edit manually. */

module harvest::crow_charges {
    use sui::bcs::{to_bytes};
    use dubhe::dapp_service::UserStorage;
    use dubhe::dapp_system;
    use harvest::dapp_key;
    use harvest::dapp_key::DappKey;


    const TABLE_NAME: vector<u8> = b"crow_charges";
    const OFFCHAIN: bool = false;

    public struct CrowCharges has copy, drop, store {
        count: u8,
        last_refill_at: u64,
    }

    public fun new(count: u8, last_refill_at: u64): CrowCharges {
        CrowCharges {
            count,
            last_refill_at,
        }
    }

    public fun count(self: &CrowCharges): u8 {
        self.count
    }

    public fun last_refill_at(self: &CrowCharges): u64 {
        self.last_refill_at
    }

    public fun update_count(self: &mut CrowCharges, count: u8) {
        self.count = count
    }

    public fun update_last_refill_at(self: &mut CrowCharges, last_refill_at: u64) {
        self.last_refill_at = last_refill_at
    }

    public fun has(user_storage: &UserStorage): bool {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        dapp_system::has_record<DappKey>(user_storage, key_tuple)
    }

    public fun ensure_has(user_storage: &UserStorage) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        dapp_system::ensure_has_record<DappKey>(user_storage, key_tuple)
    }

    public fun ensure_has_not(user_storage: &UserStorage) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        dapp_system::ensure_has_not_record<DappKey>(user_storage, key_tuple)
    }
  

    public(package) fun delete(user_storage: &mut UserStorage, ctx: &TxContext) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        dapp_system::delete_record<DappKey>(dapp_key::new(), user_storage, key_tuple, vector[b"count", b"last_refill_at"], ctx);
    }

    public fun get_count(user_storage: &UserStorage): u8 {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        let count_raw = dapp_system::get_field<DappKey>(user_storage, key_tuple, b"count");
        let mut count_bcs = sui::bcs::new(count_raw);
        let count = sui::bcs::peel_u8(&mut count_bcs);
        count
    }

    public(package) fun set_count(user_storage: &mut UserStorage, count: u8, ctx: &mut TxContext) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        let value = to_bytes(&count);
        dapp_system::set_field<DappKey>(dapp_key::new(), user_storage, key_tuple, b"count", value, ctx);
    }

    public fun get_last_refill_at(user_storage: &UserStorage): u64 {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        let last_refill_at_raw = dapp_system::get_field<DappKey>(user_storage, key_tuple, b"last_refill_at");
        let mut last_refill_at_bcs = sui::bcs::new(last_refill_at_raw);
        let last_refill_at = sui::bcs::peel_u64(&mut last_refill_at_bcs);
        last_refill_at
    }

    public(package) fun set_last_refill_at(user_storage: &mut UserStorage, last_refill_at: u64, ctx: &mut TxContext) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        let value = to_bytes(&last_refill_at);
        dapp_system::set_field<DappKey>(dapp_key::new(), user_storage, key_tuple, b"last_refill_at", value, ctx);
    }

    public fun get(user_storage: &UserStorage): (u8, u64) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        let count_raw = dapp_system::get_field<DappKey>(user_storage, key_tuple, b"count");
        let mut count_bcs = sui::bcs::new(count_raw);
        let count = sui::bcs::peel_u8(&mut count_bcs);
        let last_refill_at_raw = dapp_system::get_field<DappKey>(user_storage, key_tuple, b"last_refill_at");
        let mut last_refill_at_bcs = sui::bcs::new(last_refill_at_raw);
        let last_refill_at = sui::bcs::peel_u64(&mut last_refill_at_bcs);
        (count, last_refill_at)
    }

    public(package) fun set(user_storage: &mut UserStorage, count: u8, last_refill_at: u64, ctx: &mut TxContext) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        let field_names = vector[b"count", b"last_refill_at"];
        let value_tuple = encode(count, last_refill_at);
        dapp_system::set_record<DappKey>(dapp_key::new(), user_storage, key_tuple, field_names, value_tuple, OFFCHAIN, ctx);
    }

    public fun get_struct(user_storage: &UserStorage): CrowCharges {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        let count_raw = dapp_system::get_field<DappKey>(user_storage, key_tuple, b"count");
        let mut count_bcs = sui::bcs::new(count_raw);
        let count = sui::bcs::peel_u8(&mut count_bcs);
        let last_refill_at_raw = dapp_system::get_field<DappKey>(user_storage, key_tuple, b"last_refill_at");
        let mut last_refill_at_bcs = sui::bcs::new(last_refill_at_raw);
        let last_refill_at = sui::bcs::peel_u64(&mut last_refill_at_bcs);
        CrowCharges { count, last_refill_at }
    }

    public(package) fun set_struct(user_storage: &mut UserStorage, crow_charges: CrowCharges, ctx: &mut TxContext) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        let field_names = vector[b"count", b"last_refill_at"];
        let value_tuple = encode_struct(crow_charges);
        dapp_system::set_record<DappKey>(dapp_key::new(), user_storage, key_tuple, field_names, value_tuple, OFFCHAIN, ctx);
    }

    public fun encode(count: u8, last_refill_at: u64): vector<vector<u8>> {
        let mut value_tuple = vector::empty();
        value_tuple.push_back(to_bytes(&count));
        value_tuple.push_back(to_bytes(&last_refill_at));
        value_tuple
    }

    public fun encode_struct(crow_charges: CrowCharges): vector<vector<u8>> {
        encode(crow_charges.count, crow_charges.last_refill_at)
    }

    public fun decode(data: vector<u8>): CrowCharges {
        let mut bcs_type = sui::bcs::new(data);
        let count = sui::bcs::peel_u8(&mut bcs_type);
        let last_refill_at = sui::bcs::peel_u64(&mut bcs_type);
        CrowCharges {
            count,
            last_refill_at,
        }
    }
}