// Copyright (c) Obelisk Labs, Inc.
// SPDX-License-Identifier: Apache-2.0

/* Autogenerated file. Do not edit manually. */

module harvest::crow_damage {
    use sui::bcs::{to_bytes};
    use dubhe::dapp_service::UserStorage;
    use dubhe::dapp_service::ScenePermit;
    use dubhe::dapp_system;
    use harvest::dapp_key;
    use harvest::dapp_key::DappKey;


    const TABLE_NAME: vector<u8> = b"crow_damage";
    const OFFCHAIN: bool = false;

    public struct CrowDamage has copy, drop, store {
        expires_at: u64,
        damage_pct: u8,
    }

    public fun new(expires_at: u64, damage_pct: u8): CrowDamage {
        CrowDamage {
            expires_at,
            damage_pct,
        }
    }

    public fun expires_at(self: &CrowDamage): u64 {
        self.expires_at
    }

    public fun damage_pct(self: &CrowDamage): u8 {
        self.damage_pct
    }

    public fun update_expires_at(self: &mut CrowDamage, expires_at: u64) {
        self.expires_at = expires_at
    }

    public fun update_damage_pct(self: &mut CrowDamage, damage_pct: u8) {
        self.damage_pct = damage_pct
    }

    public fun has(user_storage: &UserStorage): bool {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        dapp_system::has_record<DappKey>(user_storage, key_tuple)
    }

    public fun ensure_has(user_storage: &UserStorage) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        dapp_system::ensure_has_record<DappKey>(user_storage, key_tuple)
    }

    public fun ensure_has_not(user_storage: &UserStorage) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        dapp_system::ensure_has_not_record<DappKey>(user_storage, key_tuple)
    }
  

    public(package) fun delete(user_storage: &mut UserStorage, ctx: &TxContext) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        dapp_system::delete_record<DappKey>(dapp_key::new(), user_storage, key_tuple, vector[b"expires_at", b"damage_pct"], ctx);
    }

    public fun get_expires_at(user_storage: &UserStorage): u64 {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        let expires_at_raw = dapp_system::get_field<DappKey>(user_storage, key_tuple, b"expires_at");
        let mut expires_at_bcs = sui::bcs::new(expires_at_raw);
        let expires_at = sui::bcs::peel_u64(&mut expires_at_bcs);
        expires_at
    }

    public(package) fun set_expires_at(user_storage: &mut UserStorage, expires_at: u64, ctx: &mut TxContext) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        let value = to_bytes(&expires_at);
        dapp_system::set_field<DappKey>(dapp_key::new(), user_storage, key_tuple, b"expires_at", value, ctx);
    }

    public fun get_damage_pct(user_storage: &UserStorage): u8 {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        let damage_pct_raw = dapp_system::get_field<DappKey>(user_storage, key_tuple, b"damage_pct");
        let mut damage_pct_bcs = sui::bcs::new(damage_pct_raw);
        let damage_pct = sui::bcs::peel_u8(&mut damage_pct_bcs);
        damage_pct
    }

    public(package) fun set_damage_pct(user_storage: &mut UserStorage, damage_pct: u8, ctx: &mut TxContext) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        let value = to_bytes(&damage_pct);
        dapp_system::set_field<DappKey>(dapp_key::new(), user_storage, key_tuple, b"damage_pct", value, ctx);
    }

    public fun get(user_storage: &UserStorage): (u64, u8) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        let expires_at_raw = dapp_system::get_field<DappKey>(user_storage, key_tuple, b"expires_at");
        let mut expires_at_bcs = sui::bcs::new(expires_at_raw);
        let expires_at = sui::bcs::peel_u64(&mut expires_at_bcs);
        let damage_pct_raw = dapp_system::get_field<DappKey>(user_storage, key_tuple, b"damage_pct");
        let mut damage_pct_bcs = sui::bcs::new(damage_pct_raw);
        let damage_pct = sui::bcs::peel_u8(&mut damage_pct_bcs);
        (expires_at, damage_pct)
    }

    public(package) fun set(user_storage: &mut UserStorage, expires_at: u64, damage_pct: u8, ctx: &mut TxContext) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        let field_names = vector[b"expires_at", b"damage_pct"];
        let value_tuple = encode(expires_at, damage_pct);
        dapp_system::set_record<DappKey>(dapp_key::new(), user_storage, key_tuple, field_names, value_tuple, OFFCHAIN, ctx);
    }

    public fun get_struct(user_storage: &UserStorage): CrowDamage {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        let expires_at_raw = dapp_system::get_field<DappKey>(user_storage, key_tuple, b"expires_at");
        let mut expires_at_bcs = sui::bcs::new(expires_at_raw);
        let expires_at = sui::bcs::peel_u64(&mut expires_at_bcs);
        let damage_pct_raw = dapp_system::get_field<DappKey>(user_storage, key_tuple, b"damage_pct");
        let mut damage_pct_bcs = sui::bcs::new(damage_pct_raw);
        let damage_pct = sui::bcs::peel_u8(&mut damage_pct_bcs);
        CrowDamage { expires_at, damage_pct }
    }

    public(package) fun set_struct(user_storage: &mut UserStorage, crow_damage: CrowDamage, ctx: &mut TxContext) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        let field_names = vector[b"expires_at", b"damage_pct"];
        let value_tuple = encode_struct(crow_damage);
        dapp_system::set_record<DappKey>(dapp_key::new(), user_storage, key_tuple, field_names, value_tuple, OFFCHAIN, ctx);
    }

    public fun encode(expires_at: u64, damage_pct: u8): vector<vector<u8>> {
        let mut value_tuple = vector::empty();
        value_tuple.push_back(to_bytes(&expires_at));
        value_tuple.push_back(to_bytes(&damage_pct));
        value_tuple
    }

    public fun encode_struct(crow_damage: CrowDamage): vector<vector<u8>> {
        encode(crow_damage.expires_at, crow_damage.damage_pct)
    }

    public fun decode(data: vector<u8>): CrowDamage {
        let mut bcs_type = sui::bcs::new(data);
        let expires_at = sui::bcs::peel_u64(&mut bcs_type);
        let damage_pct = sui::bcs::peel_u8(&mut bcs_type);
        CrowDamage {
            expires_at,
            damage_pct,
        }
    }


    // ─── reactive: cross-user write variants ───────────────────────────
    // Package-level helpers: add pause checks and access control in your system
    // functions before calling these.
    public(package) fun set_reactive<PermType>(
        permit: &ScenePermit<PermType>,
        from:   &mut UserStorage,
        target: &mut UserStorage,
        expires_at: u64, damage_pct: u8,
        ctx:    &mut TxContext,
    ) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        let field_names = vector[b"expires_at", b"damage_pct"];
        let value_tuple = encode(expires_at, damage_pct);
        dapp_system::set_record_reactive<DappKey, PermType>(dapp_key::new(), permit, from, target, key_tuple, field_names, value_tuple, ctx);
    }

    public(package) fun set_expires_at_reactive<PermType>(
        permit: &ScenePermit<PermType>,
        from:   &mut UserStorage,
        target: &mut UserStorage,
        expires_at: u64,
        ctx:    &mut TxContext,
    ) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        let value = sui::bcs::to_bytes(&expires_at);
        dapp_system::set_field_reactive<DappKey, PermType>(dapp_key::new(), permit, from, target, key_tuple, b"expires_at", value, ctx);
    }

    public(package) fun set_damage_pct_reactive<PermType>(
        permit: &ScenePermit<PermType>,
        from:   &mut UserStorage,
        target: &mut UserStorage,
        damage_pct: u8,
        ctx:    &mut TxContext,
    ) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        let value = sui::bcs::to_bytes(&damage_pct);
        dapp_system::set_field_reactive<DappKey, PermType>(dapp_key::new(), permit, from, target, key_tuple, b"damage_pct", value, ctx);
    }
}