// Copyright (c) Obelisk Labs, Inc.
// SPDX-License-Identifier: Apache-2.0

/* Autogenerated file. Do not edit manually. */

module harvest::farm_plot {
    use sui::bcs::{to_bytes};
    use dubhe::dapp_service::UserStorage;
    use dubhe::dapp_system;
    use harvest::dapp_key;
    use harvest::dapp_key::DappKey;


    const TABLE_NAME: vector<u8> = b"farm_plot";
    const OFFCHAIN: bool = false;

    public struct FarmPlot has copy, drop, store {
        crop_type: u8,
        count: u64,
        planted_at: u64,
        harvest_at: u64,
    }

    public fun new(crop_type: u8, count: u64, planted_at: u64, harvest_at: u64): FarmPlot {
        FarmPlot {
            crop_type,
            count,
            planted_at,
            harvest_at,
        }
    }

    public fun crop_type(self: &FarmPlot): u8 {
        self.crop_type
    }

    public fun count(self: &FarmPlot): u64 {
        self.count
    }

    public fun planted_at(self: &FarmPlot): u64 {
        self.planted_at
    }

    public fun harvest_at(self: &FarmPlot): u64 {
        self.harvest_at
    }

    public fun update_crop_type(self: &mut FarmPlot, crop_type: u8) {
        self.crop_type = crop_type
    }

    public fun update_count(self: &mut FarmPlot, count: u64) {
        self.count = count
    }

    public fun update_planted_at(self: &mut FarmPlot, planted_at: u64) {
        self.planted_at = planted_at
    }

    public fun update_harvest_at(self: &mut FarmPlot, harvest_at: u64) {
        self.harvest_at = harvest_at
    }

    public fun has(user_storage: &UserStorage, plot_id: u8): bool {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&plot_id));
        dapp_system::has_record<DappKey>(user_storage, key_tuple)
    }

    public fun ensure_has(user_storage: &UserStorage, plot_id: u8) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&plot_id));
        dapp_system::ensure_has_record<DappKey>(user_storage, key_tuple)
    }

    public fun ensure_has_not(user_storage: &UserStorage, plot_id: u8) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&plot_id));
        dapp_system::ensure_has_not_record<DappKey>(user_storage, key_tuple)
    }
  

    public(package) fun delete(user_storage: &mut UserStorage, plot_id: u8, ctx: &TxContext) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&plot_id));
        dapp_system::delete_record<DappKey>(dapp_key::new(), user_storage, key_tuple, vector[b"crop_type", b"count", b"planted_at", b"harvest_at"], ctx);
    }

    public fun get_crop_type(user_storage: &UserStorage, plot_id: u8): u8 {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&plot_id));
        let crop_type_raw = dapp_system::get_field<DappKey>(user_storage, key_tuple, b"crop_type");
        let mut crop_type_bcs = sui::bcs::new(crop_type_raw);
        let crop_type = sui::bcs::peel_u8(&mut crop_type_bcs);
        crop_type
    }

    public(package) fun set_crop_type(user_storage: &mut UserStorage, plot_id: u8, crop_type: u8, ctx: &mut TxContext) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&plot_id));
        let value = to_bytes(&crop_type);
        dapp_system::set_field<DappKey>(dapp_key::new(), user_storage, key_tuple, b"crop_type", value, ctx);
    }

    public fun get_count(user_storage: &UserStorage, plot_id: u8): u64 {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&plot_id));
        let count_raw = dapp_system::get_field<DappKey>(user_storage, key_tuple, b"count");
        let mut count_bcs = sui::bcs::new(count_raw);
        let count = sui::bcs::peel_u64(&mut count_bcs);
        count
    }

    public(package) fun set_count(user_storage: &mut UserStorage, plot_id: u8, count: u64, ctx: &mut TxContext) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&plot_id));
        let value = to_bytes(&count);
        dapp_system::set_field<DappKey>(dapp_key::new(), user_storage, key_tuple, b"count", value, ctx);
    }

    public fun get_planted_at(user_storage: &UserStorage, plot_id: u8): u64 {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&plot_id));
        let planted_at_raw = dapp_system::get_field<DappKey>(user_storage, key_tuple, b"planted_at");
        let mut planted_at_bcs = sui::bcs::new(planted_at_raw);
        let planted_at = sui::bcs::peel_u64(&mut planted_at_bcs);
        planted_at
    }

    public(package) fun set_planted_at(user_storage: &mut UserStorage, plot_id: u8, planted_at: u64, ctx: &mut TxContext) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&plot_id));
        let value = to_bytes(&planted_at);
        dapp_system::set_field<DappKey>(dapp_key::new(), user_storage, key_tuple, b"planted_at", value, ctx);
    }

    public fun get_harvest_at(user_storage: &UserStorage, plot_id: u8): u64 {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&plot_id));
        let harvest_at_raw = dapp_system::get_field<DappKey>(user_storage, key_tuple, b"harvest_at");
        let mut harvest_at_bcs = sui::bcs::new(harvest_at_raw);
        let harvest_at = sui::bcs::peel_u64(&mut harvest_at_bcs);
        harvest_at
    }

    public(package) fun set_harvest_at(user_storage: &mut UserStorage, plot_id: u8, harvest_at: u64, ctx: &mut TxContext) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&plot_id));
        let value = to_bytes(&harvest_at);
        dapp_system::set_field<DappKey>(dapp_key::new(), user_storage, key_tuple, b"harvest_at", value, ctx);
    }

    public fun get(user_storage: &UserStorage, plot_id: u8): (u8, u64, u64, u64) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&plot_id));
        let crop_type_raw = dapp_system::get_field<DappKey>(user_storage, key_tuple, b"crop_type");
        let mut crop_type_bcs = sui::bcs::new(crop_type_raw);
        let crop_type = sui::bcs::peel_u8(&mut crop_type_bcs);
        let count_raw = dapp_system::get_field<DappKey>(user_storage, key_tuple, b"count");
        let mut count_bcs = sui::bcs::new(count_raw);
        let count = sui::bcs::peel_u64(&mut count_bcs);
        let planted_at_raw = dapp_system::get_field<DappKey>(user_storage, key_tuple, b"planted_at");
        let mut planted_at_bcs = sui::bcs::new(planted_at_raw);
        let planted_at = sui::bcs::peel_u64(&mut planted_at_bcs);
        let harvest_at_raw = dapp_system::get_field<DappKey>(user_storage, key_tuple, b"harvest_at");
        let mut harvest_at_bcs = sui::bcs::new(harvest_at_raw);
        let harvest_at = sui::bcs::peel_u64(&mut harvest_at_bcs);
        (crop_type, count, planted_at, harvest_at)
    }

    public(package) fun set(user_storage: &mut UserStorage, plot_id: u8, crop_type: u8, count: u64, planted_at: u64, harvest_at: u64, ctx: &mut TxContext) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&plot_id));
        let field_names = vector[b"crop_type", b"count", b"planted_at", b"harvest_at"];
        let value_tuple = encode(crop_type, count, planted_at, harvest_at);
        dapp_system::set_record<DappKey>(dapp_key::new(), user_storage, key_tuple, field_names, value_tuple, OFFCHAIN, ctx);
    }

    public fun get_struct(user_storage: &UserStorage, plot_id: u8): FarmPlot {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&plot_id));
        let crop_type_raw = dapp_system::get_field<DappKey>(user_storage, key_tuple, b"crop_type");
        let mut crop_type_bcs = sui::bcs::new(crop_type_raw);
        let crop_type = sui::bcs::peel_u8(&mut crop_type_bcs);
        let count_raw = dapp_system::get_field<DappKey>(user_storage, key_tuple, b"count");
        let mut count_bcs = sui::bcs::new(count_raw);
        let count = sui::bcs::peel_u64(&mut count_bcs);
        let planted_at_raw = dapp_system::get_field<DappKey>(user_storage, key_tuple, b"planted_at");
        let mut planted_at_bcs = sui::bcs::new(planted_at_raw);
        let planted_at = sui::bcs::peel_u64(&mut planted_at_bcs);
        let harvest_at_raw = dapp_system::get_field<DappKey>(user_storage, key_tuple, b"harvest_at");
        let mut harvest_at_bcs = sui::bcs::new(harvest_at_raw);
        let harvest_at = sui::bcs::peel_u64(&mut harvest_at_bcs);
        FarmPlot { crop_type, count, planted_at, harvest_at }
    }

    public(package) fun set_struct(user_storage: &mut UserStorage, plot_id: u8, farm_plot: FarmPlot, ctx: &mut TxContext) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&plot_id));
        let field_names = vector[b"crop_type", b"count", b"planted_at", b"harvest_at"];
        let value_tuple = encode_struct(farm_plot);
        dapp_system::set_record<DappKey>(dapp_key::new(), user_storage, key_tuple, field_names, value_tuple, OFFCHAIN, ctx);
    }

    public fun encode(crop_type: u8, count: u64, planted_at: u64, harvest_at: u64): vector<vector<u8>> {
        let mut value_tuple = vector::empty();
        value_tuple.push_back(to_bytes(&crop_type));
        value_tuple.push_back(to_bytes(&count));
        value_tuple.push_back(to_bytes(&planted_at));
        value_tuple.push_back(to_bytes(&harvest_at));
        value_tuple
    }

    public fun encode_struct(farm_plot: FarmPlot): vector<vector<u8>> {
        encode(farm_plot.crop_type, farm_plot.count, farm_plot.planted_at, farm_plot.harvest_at)
    }

    public fun decode(data: vector<u8>): FarmPlot {
        let mut bcs_type = sui::bcs::new(data);
        let crop_type = sui::bcs::peel_u8(&mut bcs_type);
        let count = sui::bcs::peel_u64(&mut bcs_type);
        let planted_at = sui::bcs::peel_u64(&mut bcs_type);
        let harvest_at = sui::bcs::peel_u64(&mut bcs_type);
        FarmPlot {
            crop_type,
            count,
            planted_at,
            harvest_at,
        }
    }


    // ─── keys: mint (developer provides keys; framework ensures no duplicate) ─
    // Choosing the ID strategy (fresh address, counter, coordinate pack, etc.)
    // is intentionally left to the caller.
    public(package) fun mint(
        user_storage: &mut UserStorage,
        plot_id: u8, crop_type: u8, count: u64, planted_at: u64, harvest_at: u64,
        ctx: &mut TxContext,
    ) {
        ensure_has_not(user_storage, plot_id);
        set(user_storage, plot_id, crop_type, count, planted_at, harvest_at, ctx);
    }
}