// Copyright (c) Obelisk Labs, Inc.
// SPDX-License-Identifier: Apache-2.0

/* Autogenerated file. Do not edit manually. */

module harvest::pet {
    use sui::bcs::{to_bytes};
    use dubhe::dapp_service::{UserStorage, DappStorage};
    use dubhe::dapp_system;
    use harvest::dapp_key;
    use harvest::dapp_key::DappKey;


    const TABLE_NAME: vector<u8> = b"pet";
    const OFFCHAIN: bool = false;

    public struct Pet has copy, drop, store {
        species: u8,
        rarity: u8,
        level: u8,
        xp: u32,
        happiness: u8,
        satiety: u8,
        fed_at: u64,
        born_at: u64,
    }

    public fun new(species: u8, rarity: u8, level: u8, xp: u32, happiness: u8, satiety: u8, fed_at: u64, born_at: u64): Pet {
        Pet {
            species,
            rarity,
            level,
            xp,
            happiness,
            satiety,
            fed_at,
            born_at,
        }
    }

    public fun species(self: &Pet): u8 {
        self.species
    }

    public fun rarity(self: &Pet): u8 {
        self.rarity
    }

    public fun level(self: &Pet): u8 {
        self.level
    }

    public fun xp(self: &Pet): u32 {
        self.xp
    }

    public fun happiness(self: &Pet): u8 {
        self.happiness
    }

    public fun satiety(self: &Pet): u8 {
        self.satiety
    }

    public fun fed_at(self: &Pet): u64 {
        self.fed_at
    }

    public fun born_at(self: &Pet): u64 {
        self.born_at
    }

    public fun update_species(self: &mut Pet, species: u8) {
        self.species = species
    }

    public fun update_rarity(self: &mut Pet, rarity: u8) {
        self.rarity = rarity
    }

    public fun update_level(self: &mut Pet, level: u8) {
        self.level = level
    }

    public fun update_xp(self: &mut Pet, xp: u32) {
        self.xp = xp
    }

    public fun update_happiness(self: &mut Pet, happiness: u8) {
        self.happiness = happiness
    }

    public fun update_satiety(self: &mut Pet, satiety: u8) {
        self.satiety = satiety
    }

    public fun update_fed_at(self: &mut Pet, fed_at: u64) {
        self.fed_at = fed_at
    }

    public fun update_born_at(self: &mut Pet, born_at: u64) {
        self.born_at = born_at
    }

    public fun has(user_storage: &UserStorage, pet_id: address): bool {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&pet_id));
        dapp_system::has_record<DappKey>(user_storage, key_tuple)
    }

    public fun ensure_has(user_storage: &UserStorage, pet_id: address) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&pet_id));
        dapp_system::ensure_has_record<DappKey>(user_storage, key_tuple)
    }

    public fun ensure_has_not(user_storage: &UserStorage, pet_id: address) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&pet_id));
        dapp_system::ensure_has_not_record<DappKey>(user_storage, key_tuple)
    }
  

    public(package) fun delete(user_storage: &mut UserStorage, pet_id: address, ctx: &TxContext) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&pet_id));
        dapp_system::delete_record<DappKey>(dapp_key::new(), user_storage, key_tuple, vector[b"species", b"rarity", b"level", b"xp", b"happiness", b"satiety", b"fed_at", b"born_at"], ctx);
    }

    public fun get_species(user_storage: &UserStorage, pet_id: address): u8 {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&pet_id));
        let species_raw = dapp_system::get_field<DappKey>(user_storage, key_tuple, b"species");
        let mut species_bcs = sui::bcs::new(species_raw);
        let species = sui::bcs::peel_u8(&mut species_bcs);
        species
    }

    public(package) fun set_species(user_storage: &mut UserStorage, pet_id: address, species: u8, ctx: &mut TxContext) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&pet_id));
        let value = to_bytes(&species);
        dapp_system::set_field<DappKey>(dapp_key::new(), user_storage, key_tuple, b"species", value, ctx);
    }

    public fun get_rarity(user_storage: &UserStorage, pet_id: address): u8 {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&pet_id));
        let rarity_raw = dapp_system::get_field<DappKey>(user_storage, key_tuple, b"rarity");
        let mut rarity_bcs = sui::bcs::new(rarity_raw);
        let rarity = sui::bcs::peel_u8(&mut rarity_bcs);
        rarity
    }

    public(package) fun set_rarity(user_storage: &mut UserStorage, pet_id: address, rarity: u8, ctx: &mut TxContext) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&pet_id));
        let value = to_bytes(&rarity);
        dapp_system::set_field<DappKey>(dapp_key::new(), user_storage, key_tuple, b"rarity", value, ctx);
    }

    public fun get_level(user_storage: &UserStorage, pet_id: address): u8 {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&pet_id));
        let level_raw = dapp_system::get_field<DappKey>(user_storage, key_tuple, b"level");
        let mut level_bcs = sui::bcs::new(level_raw);
        let level = sui::bcs::peel_u8(&mut level_bcs);
        level
    }

    public(package) fun set_level(user_storage: &mut UserStorage, pet_id: address, level: u8, ctx: &mut TxContext) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&pet_id));
        let value = to_bytes(&level);
        dapp_system::set_field<DappKey>(dapp_key::new(), user_storage, key_tuple, b"level", value, ctx);
    }

    public fun get_xp(user_storage: &UserStorage, pet_id: address): u32 {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&pet_id));
        let xp_raw = dapp_system::get_field<DappKey>(user_storage, key_tuple, b"xp");
        let mut xp_bcs = sui::bcs::new(xp_raw);
        let xp = sui::bcs::peel_u32(&mut xp_bcs);
        xp
    }

    public(package) fun set_xp(user_storage: &mut UserStorage, pet_id: address, xp: u32, ctx: &mut TxContext) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&pet_id));
        let value = to_bytes(&xp);
        dapp_system::set_field<DappKey>(dapp_key::new(), user_storage, key_tuple, b"xp", value, ctx);
    }

    public fun get_happiness(user_storage: &UserStorage, pet_id: address): u8 {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&pet_id));
        let happiness_raw = dapp_system::get_field<DappKey>(user_storage, key_tuple, b"happiness");
        let mut happiness_bcs = sui::bcs::new(happiness_raw);
        let happiness = sui::bcs::peel_u8(&mut happiness_bcs);
        happiness
    }

    public(package) fun set_happiness(user_storage: &mut UserStorage, pet_id: address, happiness: u8, ctx: &mut TxContext) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&pet_id));
        let value = to_bytes(&happiness);
        dapp_system::set_field<DappKey>(dapp_key::new(), user_storage, key_tuple, b"happiness", value, ctx);
    }

    public fun get_satiety(user_storage: &UserStorage, pet_id: address): u8 {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&pet_id));
        let satiety_raw = dapp_system::get_field<DappKey>(user_storage, key_tuple, b"satiety");
        let mut satiety_bcs = sui::bcs::new(satiety_raw);
        let satiety = sui::bcs::peel_u8(&mut satiety_bcs);
        satiety
    }

    public(package) fun set_satiety(user_storage: &mut UserStorage, pet_id: address, satiety: u8, ctx: &mut TxContext) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&pet_id));
        let value = to_bytes(&satiety);
        dapp_system::set_field<DappKey>(dapp_key::new(), user_storage, key_tuple, b"satiety", value, ctx);
    }

    public fun get_fed_at(user_storage: &UserStorage, pet_id: address): u64 {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&pet_id));
        let fed_at_raw = dapp_system::get_field<DappKey>(user_storage, key_tuple, b"fed_at");
        let mut fed_at_bcs = sui::bcs::new(fed_at_raw);
        let fed_at = sui::bcs::peel_u64(&mut fed_at_bcs);
        fed_at
    }

    public(package) fun set_fed_at(user_storage: &mut UserStorage, pet_id: address, fed_at: u64, ctx: &mut TxContext) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&pet_id));
        let value = to_bytes(&fed_at);
        dapp_system::set_field<DappKey>(dapp_key::new(), user_storage, key_tuple, b"fed_at", value, ctx);
    }

    public fun get_born_at(user_storage: &UserStorage, pet_id: address): u64 {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&pet_id));
        let born_at_raw = dapp_system::get_field<DappKey>(user_storage, key_tuple, b"born_at");
        let mut born_at_bcs = sui::bcs::new(born_at_raw);
        let born_at = sui::bcs::peel_u64(&mut born_at_bcs);
        born_at
    }

    public(package) fun set_born_at(user_storage: &mut UserStorage, pet_id: address, born_at: u64, ctx: &mut TxContext) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&pet_id));
        let value = to_bytes(&born_at);
        dapp_system::set_field<DappKey>(dapp_key::new(), user_storage, key_tuple, b"born_at", value, ctx);
    }

    public fun get(user_storage: &UserStorage, pet_id: address): (u8, u8, u8, u32, u8, u8, u64, u64) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&pet_id));
        let species_raw = dapp_system::get_field<DappKey>(user_storage, key_tuple, b"species");
        let mut species_bcs = sui::bcs::new(species_raw);
        let species = sui::bcs::peel_u8(&mut species_bcs);
        let rarity_raw = dapp_system::get_field<DappKey>(user_storage, key_tuple, b"rarity");
        let mut rarity_bcs = sui::bcs::new(rarity_raw);
        let rarity = sui::bcs::peel_u8(&mut rarity_bcs);
        let level_raw = dapp_system::get_field<DappKey>(user_storage, key_tuple, b"level");
        let mut level_bcs = sui::bcs::new(level_raw);
        let level = sui::bcs::peel_u8(&mut level_bcs);
        let xp_raw = dapp_system::get_field<DappKey>(user_storage, key_tuple, b"xp");
        let mut xp_bcs = sui::bcs::new(xp_raw);
        let xp = sui::bcs::peel_u32(&mut xp_bcs);
        let happiness_raw = dapp_system::get_field<DappKey>(user_storage, key_tuple, b"happiness");
        let mut happiness_bcs = sui::bcs::new(happiness_raw);
        let happiness = sui::bcs::peel_u8(&mut happiness_bcs);
        let satiety_raw = dapp_system::get_field<DappKey>(user_storage, key_tuple, b"satiety");
        let mut satiety_bcs = sui::bcs::new(satiety_raw);
        let satiety = sui::bcs::peel_u8(&mut satiety_bcs);
        let fed_at_raw = dapp_system::get_field<DappKey>(user_storage, key_tuple, b"fed_at");
        let mut fed_at_bcs = sui::bcs::new(fed_at_raw);
        let fed_at = sui::bcs::peel_u64(&mut fed_at_bcs);
        let born_at_raw = dapp_system::get_field<DappKey>(user_storage, key_tuple, b"born_at");
        let mut born_at_bcs = sui::bcs::new(born_at_raw);
        let born_at = sui::bcs::peel_u64(&mut born_at_bcs);
        (species, rarity, level, xp, happiness, satiety, fed_at, born_at)
    }

    public(package) fun set(user_storage: &mut UserStorage, pet_id: address, species: u8, rarity: u8, level: u8, xp: u32, happiness: u8, satiety: u8, fed_at: u64, born_at: u64, ctx: &mut TxContext) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&pet_id));
        let field_names = vector[b"species", b"rarity", b"level", b"xp", b"happiness", b"satiety", b"fed_at", b"born_at"];
        let value_tuple = encode(species, rarity, level, xp, happiness, satiety, fed_at, born_at);
        dapp_system::set_record<DappKey>(dapp_key::new(), user_storage, key_tuple, field_names, value_tuple, OFFCHAIN, ctx);
    }

    public fun get_struct(user_storage: &UserStorage, pet_id: address): Pet {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&pet_id));
        let species_raw = dapp_system::get_field<DappKey>(user_storage, key_tuple, b"species");
        let mut species_bcs = sui::bcs::new(species_raw);
        let species = sui::bcs::peel_u8(&mut species_bcs);
        let rarity_raw = dapp_system::get_field<DappKey>(user_storage, key_tuple, b"rarity");
        let mut rarity_bcs = sui::bcs::new(rarity_raw);
        let rarity = sui::bcs::peel_u8(&mut rarity_bcs);
        let level_raw = dapp_system::get_field<DappKey>(user_storage, key_tuple, b"level");
        let mut level_bcs = sui::bcs::new(level_raw);
        let level = sui::bcs::peel_u8(&mut level_bcs);
        let xp_raw = dapp_system::get_field<DappKey>(user_storage, key_tuple, b"xp");
        let mut xp_bcs = sui::bcs::new(xp_raw);
        let xp = sui::bcs::peel_u32(&mut xp_bcs);
        let happiness_raw = dapp_system::get_field<DappKey>(user_storage, key_tuple, b"happiness");
        let mut happiness_bcs = sui::bcs::new(happiness_raw);
        let happiness = sui::bcs::peel_u8(&mut happiness_bcs);
        let satiety_raw = dapp_system::get_field<DappKey>(user_storage, key_tuple, b"satiety");
        let mut satiety_bcs = sui::bcs::new(satiety_raw);
        let satiety = sui::bcs::peel_u8(&mut satiety_bcs);
        let fed_at_raw = dapp_system::get_field<DappKey>(user_storage, key_tuple, b"fed_at");
        let mut fed_at_bcs = sui::bcs::new(fed_at_raw);
        let fed_at = sui::bcs::peel_u64(&mut fed_at_bcs);
        let born_at_raw = dapp_system::get_field<DappKey>(user_storage, key_tuple, b"born_at");
        let mut born_at_bcs = sui::bcs::new(born_at_raw);
        let born_at = sui::bcs::peel_u64(&mut born_at_bcs);
        Pet { species, rarity, level, xp, happiness, satiety, fed_at, born_at }
    }

    public(package) fun set_struct(user_storage: &mut UserStorage, pet_id: address, pet: Pet, ctx: &mut TxContext) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&pet_id));
        let field_names = vector[b"species", b"rarity", b"level", b"xp", b"happiness", b"satiety", b"fed_at", b"born_at"];
        let value_tuple = encode_struct(pet);
        dapp_system::set_record<DappKey>(dapp_key::new(), user_storage, key_tuple, field_names, value_tuple, OFFCHAIN, ctx);
    }

    public fun encode(species: u8, rarity: u8, level: u8, xp: u32, happiness: u8, satiety: u8, fed_at: u64, born_at: u64): vector<vector<u8>> {
        let mut value_tuple = vector::empty();
        value_tuple.push_back(to_bytes(&species));
        value_tuple.push_back(to_bytes(&rarity));
        value_tuple.push_back(to_bytes(&level));
        value_tuple.push_back(to_bytes(&xp));
        value_tuple.push_back(to_bytes(&happiness));
        value_tuple.push_back(to_bytes(&satiety));
        value_tuple.push_back(to_bytes(&fed_at));
        value_tuple.push_back(to_bytes(&born_at));
        value_tuple
    }

    public fun encode_struct(pet: Pet): vector<vector<u8>> {
        encode(pet.species, pet.rarity, pet.level, pet.xp, pet.happiness, pet.satiety, pet.fed_at, pet.born_at)
    }

    public fun decode(data: vector<u8>): Pet {
        let mut bcs_type = sui::bcs::new(data);
        let species = sui::bcs::peel_u8(&mut bcs_type);
        let rarity = sui::bcs::peel_u8(&mut bcs_type);
        let level = sui::bcs::peel_u8(&mut bcs_type);
        let xp = sui::bcs::peel_u32(&mut bcs_type);
        let happiness = sui::bcs::peel_u8(&mut bcs_type);
        let satiety = sui::bcs::peel_u8(&mut bcs_type);
        let fed_at = sui::bcs::peel_u64(&mut bcs_type);
        let born_at = sui::bcs::peel_u64(&mut bcs_type);
        Pet {
            species,
            rarity,
            level,
            xp,
            happiness,
            satiety,
            fed_at,
            born_at,
        }
    }


    // ─── keys: mint (developer provides keys; framework ensures no duplicate) ─
    // Choosing the ID strategy (fresh address, counter, coordinate pack, etc.)
    // is intentionally left to the caller.
    public(package) fun mint(
        user_storage: &mut UserStorage,
        pet_id: address, species: u8, rarity: u8, level: u8, xp: u32, happiness: u8, satiety: u8, fed_at: u64, born_at: u64,
        ctx: &mut TxContext,
    ) {
        ensure_has_not(user_storage, pet_id);
        set(user_storage, pet_id, species, rarity, level, xp, happiness, satiety, fed_at, born_at, ctx);
    }

    // ─── listable: market protocol (keyed) ──────────────────────────────
    // Package-level helpers: call these from your system functions.
    // Add pause checks, access control, and custom logic there.
    public(package) fun list<CoinType>(
        user_storage: &mut UserStorage,
        pet_id:   address,
        price:        u64,
        listed_until: std::option::Option<u64>,
        ctx:          &mut TxContext,
    ) {
        let mut record_key = vector::empty();
        record_key.push_back(TABLE_NAME);
        record_key.push_back(sui::bcs::to_bytes(&pet_id));
        dubhe::dapp_system::take_record<DappKey, CoinType>(
            dapp_key::new(),
            user_storage,
            b"pet",
            record_key,
            vector[b"species", b"rarity", b"level", b"xp", b"happiness", b"satiety", b"fed_at", b"born_at"],
            price,
            listed_until,
            ctx,
        );
    }

    public(package) fun buy<CoinType>(
        dh:            &dubhe::dapp_service::DappHub,
        dapp_storage:  &mut DappStorage,
        listing:       dubhe::dapp_service::Listing<CoinType>,
        user_storage:  &mut UserStorage,
        payment:       sui::coin::Coin<CoinType>,
        ctx:           &mut TxContext,
    ): sui::coin::Coin<CoinType> {
        dubhe::dapp_system::buy_record<DappKey, CoinType>(
            dapp_key::new(), dh, dapp_storage, listing, user_storage, payment, ctx
        )
    }

    public(package) fun cancel_listing<CoinType>(
        listing:      dubhe::dapp_service::Listing<CoinType>,
        user_storage: &mut UserStorage,
        ctx:          &TxContext,
    ) {
        dubhe::dapp_system::restore_record<DappKey, CoinType>(
            dapp_key::new(), listing, user_storage, ctx
        );
    }

    public(package) fun expire_listing<CoinType>(
        listing:      dubhe::dapp_service::Listing<CoinType>,
        user_storage: &mut UserStorage,
        ctx:          &TxContext,
    ) {
        dubhe::dapp_system::expire_listing<DappKey, CoinType>(
            dapp_key::new(), listing, user_storage, ctx
        );
    }
}