// Copyright (c) Obelisk Labs, Inc.
// SPDX-License-Identifier: Apache-2.0

/* Autogenerated file. Do not edit manually. */

module harvest::pet_config {
    use sui::bcs::{to_bytes};
    use dubhe::dapp_service::DappStorage;
    use dubhe::dapp_system;
    use harvest::dapp_key;
    use harvest::dapp_key::DappKey;


    const TABLE_NAME: vector<u8> = b"pet_config";
    const OFFCHAIN: bool = false;

    public struct PetConfig has copy, drop, store {
        common_egg_price: u64,
        rare_egg_price: u64,
        seasonal_egg_price: u64,
        common_hatch_ms: u64,
        rare_hatch_ms: u64,
        seasonal_hatch_ms: u64,
        slot2_price: u64,
        slot3_price: u64,
    }

    public fun new(common_egg_price: u64, rare_egg_price: u64, seasonal_egg_price: u64, common_hatch_ms: u64, rare_hatch_ms: u64, seasonal_hatch_ms: u64, slot2_price: u64, slot3_price: u64): PetConfig {
        PetConfig {
            common_egg_price,
            rare_egg_price,
            seasonal_egg_price,
            common_hatch_ms,
            rare_hatch_ms,
            seasonal_hatch_ms,
            slot2_price,
            slot3_price,
        }
    }

    public fun common_egg_price(self: &PetConfig): u64 {
        self.common_egg_price
    }

    public fun rare_egg_price(self: &PetConfig): u64 {
        self.rare_egg_price
    }

    public fun seasonal_egg_price(self: &PetConfig): u64 {
        self.seasonal_egg_price
    }

    public fun common_hatch_ms(self: &PetConfig): u64 {
        self.common_hatch_ms
    }

    public fun rare_hatch_ms(self: &PetConfig): u64 {
        self.rare_hatch_ms
    }

    public fun seasonal_hatch_ms(self: &PetConfig): u64 {
        self.seasonal_hatch_ms
    }

    public fun slot2_price(self: &PetConfig): u64 {
        self.slot2_price
    }

    public fun slot3_price(self: &PetConfig): u64 {
        self.slot3_price
    }

    public fun update_common_egg_price(self: &mut PetConfig, common_egg_price: u64) {
        self.common_egg_price = common_egg_price
    }

    public fun update_rare_egg_price(self: &mut PetConfig, rare_egg_price: u64) {
        self.rare_egg_price = rare_egg_price
    }

    public fun update_seasonal_egg_price(self: &mut PetConfig, seasonal_egg_price: u64) {
        self.seasonal_egg_price = seasonal_egg_price
    }

    public fun update_common_hatch_ms(self: &mut PetConfig, common_hatch_ms: u64) {
        self.common_hatch_ms = common_hatch_ms
    }

    public fun update_rare_hatch_ms(self: &mut PetConfig, rare_hatch_ms: u64) {
        self.rare_hatch_ms = rare_hatch_ms
    }

    public fun update_seasonal_hatch_ms(self: &mut PetConfig, seasonal_hatch_ms: u64) {
        self.seasonal_hatch_ms = seasonal_hatch_ms
    }

    public fun update_slot2_price(self: &mut PetConfig, slot2_price: u64) {
        self.slot2_price = slot2_price
    }

    public fun update_slot3_price(self: &mut PetConfig, slot3_price: u64) {
        self.slot3_price = slot3_price
    }

    public fun has(dapp_storage: &DappStorage): bool {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        dapp_system::has_global_record<DappKey>(dapp_storage, key_tuple)
    }

    public fun ensure_has(dapp_storage: &DappStorage) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        dapp_system::ensure_has_global_record<DappKey>(dapp_storage, key_tuple)
    }

    public fun ensure_has_not(dapp_storage: &DappStorage) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        dapp_system::ensure_has_not_global_record<DappKey>(dapp_storage, key_tuple)
    }
  

    public(package) fun delete(dapp_storage: &mut DappStorage) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        dapp_system::delete_global_record<DappKey>(dapp_key::new(), dapp_storage, key_tuple, vector[b"common_egg_price", b"rare_egg_price", b"seasonal_egg_price", b"common_hatch_ms", b"rare_hatch_ms", b"seasonal_hatch_ms", b"slot2_price", b"slot3_price"]);
    }

    public fun get_common_egg_price(dapp_storage: &DappStorage): u64 {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        let common_egg_price_raw = dapp_system::get_global_field<DappKey>(dapp_storage, key_tuple, b"common_egg_price");
        let mut common_egg_price_bcs = sui::bcs::new(common_egg_price_raw);
        let common_egg_price = sui::bcs::peel_u64(&mut common_egg_price_bcs);
        common_egg_price
    }

    public(package) fun set_common_egg_price(dapp_storage: &mut DappStorage, common_egg_price: u64) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        let value = to_bytes(&common_egg_price);
        dapp_system::set_global_field<DappKey>(dapp_key::new(), dapp_storage, key_tuple, b"common_egg_price", value);
    }

    public fun get_rare_egg_price(dapp_storage: &DappStorage): u64 {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        let rare_egg_price_raw = dapp_system::get_global_field<DappKey>(dapp_storage, key_tuple, b"rare_egg_price");
        let mut rare_egg_price_bcs = sui::bcs::new(rare_egg_price_raw);
        let rare_egg_price = sui::bcs::peel_u64(&mut rare_egg_price_bcs);
        rare_egg_price
    }

    public(package) fun set_rare_egg_price(dapp_storage: &mut DappStorage, rare_egg_price: u64) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        let value = to_bytes(&rare_egg_price);
        dapp_system::set_global_field<DappKey>(dapp_key::new(), dapp_storage, key_tuple, b"rare_egg_price", value);
    }

    public fun get_seasonal_egg_price(dapp_storage: &DappStorage): u64 {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        let seasonal_egg_price_raw = dapp_system::get_global_field<DappKey>(dapp_storage, key_tuple, b"seasonal_egg_price");
        let mut seasonal_egg_price_bcs = sui::bcs::new(seasonal_egg_price_raw);
        let seasonal_egg_price = sui::bcs::peel_u64(&mut seasonal_egg_price_bcs);
        seasonal_egg_price
    }

    public(package) fun set_seasonal_egg_price(dapp_storage: &mut DappStorage, seasonal_egg_price: u64) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        let value = to_bytes(&seasonal_egg_price);
        dapp_system::set_global_field<DappKey>(dapp_key::new(), dapp_storage, key_tuple, b"seasonal_egg_price", value);
    }

    public fun get_common_hatch_ms(dapp_storage: &DappStorage): u64 {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        let common_hatch_ms_raw = dapp_system::get_global_field<DappKey>(dapp_storage, key_tuple, b"common_hatch_ms");
        let mut common_hatch_ms_bcs = sui::bcs::new(common_hatch_ms_raw);
        let common_hatch_ms = sui::bcs::peel_u64(&mut common_hatch_ms_bcs);
        common_hatch_ms
    }

    public(package) fun set_common_hatch_ms(dapp_storage: &mut DappStorage, common_hatch_ms: u64) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        let value = to_bytes(&common_hatch_ms);
        dapp_system::set_global_field<DappKey>(dapp_key::new(), dapp_storage, key_tuple, b"common_hatch_ms", value);
    }

    public fun get_rare_hatch_ms(dapp_storage: &DappStorage): u64 {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        let rare_hatch_ms_raw = dapp_system::get_global_field<DappKey>(dapp_storage, key_tuple, b"rare_hatch_ms");
        let mut rare_hatch_ms_bcs = sui::bcs::new(rare_hatch_ms_raw);
        let rare_hatch_ms = sui::bcs::peel_u64(&mut rare_hatch_ms_bcs);
        rare_hatch_ms
    }

    public(package) fun set_rare_hatch_ms(dapp_storage: &mut DappStorage, rare_hatch_ms: u64) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        let value = to_bytes(&rare_hatch_ms);
        dapp_system::set_global_field<DappKey>(dapp_key::new(), dapp_storage, key_tuple, b"rare_hatch_ms", value);
    }

    public fun get_seasonal_hatch_ms(dapp_storage: &DappStorage): u64 {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        let seasonal_hatch_ms_raw = dapp_system::get_global_field<DappKey>(dapp_storage, key_tuple, b"seasonal_hatch_ms");
        let mut seasonal_hatch_ms_bcs = sui::bcs::new(seasonal_hatch_ms_raw);
        let seasonal_hatch_ms = sui::bcs::peel_u64(&mut seasonal_hatch_ms_bcs);
        seasonal_hatch_ms
    }

    public(package) fun set_seasonal_hatch_ms(dapp_storage: &mut DappStorage, seasonal_hatch_ms: u64) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        let value = to_bytes(&seasonal_hatch_ms);
        dapp_system::set_global_field<DappKey>(dapp_key::new(), dapp_storage, key_tuple, b"seasonal_hatch_ms", value);
    }

    public fun get_slot2_price(dapp_storage: &DappStorage): u64 {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        let slot2_price_raw = dapp_system::get_global_field<DappKey>(dapp_storage, key_tuple, b"slot2_price");
        let mut slot2_price_bcs = sui::bcs::new(slot2_price_raw);
        let slot2_price = sui::bcs::peel_u64(&mut slot2_price_bcs);
        slot2_price
    }

    public(package) fun set_slot2_price(dapp_storage: &mut DappStorage, slot2_price: u64) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        let value = to_bytes(&slot2_price);
        dapp_system::set_global_field<DappKey>(dapp_key::new(), dapp_storage, key_tuple, b"slot2_price", value);
    }

    public fun get_slot3_price(dapp_storage: &DappStorage): u64 {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        let slot3_price_raw = dapp_system::get_global_field<DappKey>(dapp_storage, key_tuple, b"slot3_price");
        let mut slot3_price_bcs = sui::bcs::new(slot3_price_raw);
        let slot3_price = sui::bcs::peel_u64(&mut slot3_price_bcs);
        slot3_price
    }

    public(package) fun set_slot3_price(dapp_storage: &mut DappStorage, slot3_price: u64) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        let value = to_bytes(&slot3_price);
        dapp_system::set_global_field<DappKey>(dapp_key::new(), dapp_storage, key_tuple, b"slot3_price", value);
    }

    public fun get(dapp_storage: &DappStorage): (u64, u64, u64, u64, u64, u64, u64, u64) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        let common_egg_price_raw = dapp_system::get_global_field<DappKey>(dapp_storage, key_tuple, b"common_egg_price");
        let mut common_egg_price_bcs = sui::bcs::new(common_egg_price_raw);
        let common_egg_price = sui::bcs::peel_u64(&mut common_egg_price_bcs);
        let rare_egg_price_raw = dapp_system::get_global_field<DappKey>(dapp_storage, key_tuple, b"rare_egg_price");
        let mut rare_egg_price_bcs = sui::bcs::new(rare_egg_price_raw);
        let rare_egg_price = sui::bcs::peel_u64(&mut rare_egg_price_bcs);
        let seasonal_egg_price_raw = dapp_system::get_global_field<DappKey>(dapp_storage, key_tuple, b"seasonal_egg_price");
        let mut seasonal_egg_price_bcs = sui::bcs::new(seasonal_egg_price_raw);
        let seasonal_egg_price = sui::bcs::peel_u64(&mut seasonal_egg_price_bcs);
        let common_hatch_ms_raw = dapp_system::get_global_field<DappKey>(dapp_storage, key_tuple, b"common_hatch_ms");
        let mut common_hatch_ms_bcs = sui::bcs::new(common_hatch_ms_raw);
        let common_hatch_ms = sui::bcs::peel_u64(&mut common_hatch_ms_bcs);
        let rare_hatch_ms_raw = dapp_system::get_global_field<DappKey>(dapp_storage, key_tuple, b"rare_hatch_ms");
        let mut rare_hatch_ms_bcs = sui::bcs::new(rare_hatch_ms_raw);
        let rare_hatch_ms = sui::bcs::peel_u64(&mut rare_hatch_ms_bcs);
        let seasonal_hatch_ms_raw = dapp_system::get_global_field<DappKey>(dapp_storage, key_tuple, b"seasonal_hatch_ms");
        let mut seasonal_hatch_ms_bcs = sui::bcs::new(seasonal_hatch_ms_raw);
        let seasonal_hatch_ms = sui::bcs::peel_u64(&mut seasonal_hatch_ms_bcs);
        let slot2_price_raw = dapp_system::get_global_field<DappKey>(dapp_storage, key_tuple, b"slot2_price");
        let mut slot2_price_bcs = sui::bcs::new(slot2_price_raw);
        let slot2_price = sui::bcs::peel_u64(&mut slot2_price_bcs);
        let slot3_price_raw = dapp_system::get_global_field<DappKey>(dapp_storage, key_tuple, b"slot3_price");
        let mut slot3_price_bcs = sui::bcs::new(slot3_price_raw);
        let slot3_price = sui::bcs::peel_u64(&mut slot3_price_bcs);
        (common_egg_price, rare_egg_price, seasonal_egg_price, common_hatch_ms, rare_hatch_ms, seasonal_hatch_ms, slot2_price, slot3_price)
    }

    public(package) fun set(dapp_storage: &mut DappStorage, common_egg_price: u64, rare_egg_price: u64, seasonal_egg_price: u64, common_hatch_ms: u64, rare_hatch_ms: u64, seasonal_hatch_ms: u64, slot2_price: u64, slot3_price: u64) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        let field_names = vector[b"common_egg_price", b"rare_egg_price", b"seasonal_egg_price", b"common_hatch_ms", b"rare_hatch_ms", b"seasonal_hatch_ms", b"slot2_price", b"slot3_price"];
        let value_tuple = encode(common_egg_price, rare_egg_price, seasonal_egg_price, common_hatch_ms, rare_hatch_ms, seasonal_hatch_ms, slot2_price, slot3_price);
        dapp_system::set_global_record<DappKey>(dapp_key::new(), dapp_storage, key_tuple, field_names, value_tuple, OFFCHAIN);
    }

    public fun get_struct(dapp_storage: &DappStorage): PetConfig {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        let common_egg_price_raw = dapp_system::get_global_field<DappKey>(dapp_storage, key_tuple, b"common_egg_price");
        let mut common_egg_price_bcs = sui::bcs::new(common_egg_price_raw);
        let common_egg_price = sui::bcs::peel_u64(&mut common_egg_price_bcs);
        let rare_egg_price_raw = dapp_system::get_global_field<DappKey>(dapp_storage, key_tuple, b"rare_egg_price");
        let mut rare_egg_price_bcs = sui::bcs::new(rare_egg_price_raw);
        let rare_egg_price = sui::bcs::peel_u64(&mut rare_egg_price_bcs);
        let seasonal_egg_price_raw = dapp_system::get_global_field<DappKey>(dapp_storage, key_tuple, b"seasonal_egg_price");
        let mut seasonal_egg_price_bcs = sui::bcs::new(seasonal_egg_price_raw);
        let seasonal_egg_price = sui::bcs::peel_u64(&mut seasonal_egg_price_bcs);
        let common_hatch_ms_raw = dapp_system::get_global_field<DappKey>(dapp_storage, key_tuple, b"common_hatch_ms");
        let mut common_hatch_ms_bcs = sui::bcs::new(common_hatch_ms_raw);
        let common_hatch_ms = sui::bcs::peel_u64(&mut common_hatch_ms_bcs);
        let rare_hatch_ms_raw = dapp_system::get_global_field<DappKey>(dapp_storage, key_tuple, b"rare_hatch_ms");
        let mut rare_hatch_ms_bcs = sui::bcs::new(rare_hatch_ms_raw);
        let rare_hatch_ms = sui::bcs::peel_u64(&mut rare_hatch_ms_bcs);
        let seasonal_hatch_ms_raw = dapp_system::get_global_field<DappKey>(dapp_storage, key_tuple, b"seasonal_hatch_ms");
        let mut seasonal_hatch_ms_bcs = sui::bcs::new(seasonal_hatch_ms_raw);
        let seasonal_hatch_ms = sui::bcs::peel_u64(&mut seasonal_hatch_ms_bcs);
        let slot2_price_raw = dapp_system::get_global_field<DappKey>(dapp_storage, key_tuple, b"slot2_price");
        let mut slot2_price_bcs = sui::bcs::new(slot2_price_raw);
        let slot2_price = sui::bcs::peel_u64(&mut slot2_price_bcs);
        let slot3_price_raw = dapp_system::get_global_field<DappKey>(dapp_storage, key_tuple, b"slot3_price");
        let mut slot3_price_bcs = sui::bcs::new(slot3_price_raw);
        let slot3_price = sui::bcs::peel_u64(&mut slot3_price_bcs);
        PetConfig { common_egg_price, rare_egg_price, seasonal_egg_price, common_hatch_ms, rare_hatch_ms, seasonal_hatch_ms, slot2_price, slot3_price }
    }

    public(package) fun set_struct(dapp_storage: &mut DappStorage, pet_config: PetConfig) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        let field_names = vector[b"common_egg_price", b"rare_egg_price", b"seasonal_egg_price", b"common_hatch_ms", b"rare_hatch_ms", b"seasonal_hatch_ms", b"slot2_price", b"slot3_price"];
        let value_tuple = encode_struct(pet_config);
        dapp_system::set_global_record<DappKey>(dapp_key::new(), dapp_storage, key_tuple, field_names, value_tuple, OFFCHAIN);
    }

    public fun encode(common_egg_price: u64, rare_egg_price: u64, seasonal_egg_price: u64, common_hatch_ms: u64, rare_hatch_ms: u64, seasonal_hatch_ms: u64, slot2_price: u64, slot3_price: u64): vector<vector<u8>> {
        let mut value_tuple = vector::empty();
        value_tuple.push_back(to_bytes(&common_egg_price));
        value_tuple.push_back(to_bytes(&rare_egg_price));
        value_tuple.push_back(to_bytes(&seasonal_egg_price));
        value_tuple.push_back(to_bytes(&common_hatch_ms));
        value_tuple.push_back(to_bytes(&rare_hatch_ms));
        value_tuple.push_back(to_bytes(&seasonal_hatch_ms));
        value_tuple.push_back(to_bytes(&slot2_price));
        value_tuple.push_back(to_bytes(&slot3_price));
        value_tuple
    }

    public fun encode_struct(pet_config: PetConfig): vector<vector<u8>> {
        encode(pet_config.common_egg_price, pet_config.rare_egg_price, pet_config.seasonal_egg_price, pet_config.common_hatch_ms, pet_config.rare_hatch_ms, pet_config.seasonal_hatch_ms, pet_config.slot2_price, pet_config.slot3_price)
    }

    public fun decode(data: vector<u8>): PetConfig {
        let mut bcs_type = sui::bcs::new(data);
        let common_egg_price = sui::bcs::peel_u64(&mut bcs_type);
        let rare_egg_price = sui::bcs::peel_u64(&mut bcs_type);
        let seasonal_egg_price = sui::bcs::peel_u64(&mut bcs_type);
        let common_hatch_ms = sui::bcs::peel_u64(&mut bcs_type);
        let rare_hatch_ms = sui::bcs::peel_u64(&mut bcs_type);
        let seasonal_hatch_ms = sui::bcs::peel_u64(&mut bcs_type);
        let slot2_price = sui::bcs::peel_u64(&mut bcs_type);
        let slot3_price = sui::bcs::peel_u64(&mut bcs_type);
        PetConfig {
            common_egg_price,
            rare_egg_price,
            seasonal_egg_price,
            common_hatch_ms,
            rare_hatch_ms,
            seasonal_hatch_ms,
            slot2_price,
            slot3_price,
        }
    }
}