// Copyright (c) Obelisk Labs, Inc.
// SPDX-License-Identifier: Apache-2.0

/* Autogenerated file. Do not edit manually. */

module harvest::pet_slot_index {
    use sui::bcs::{to_bytes};
    use dubhe::dapp_service::UserStorage;
    use dubhe::dapp_system;
    use harvest::dapp_key;
    use harvest::dapp_key::DappKey;


    const TABLE_NAME: vector<u8> = b"pet_slot_index";
    const OFFCHAIN: bool = false;

    public fun has(user_storage: &UserStorage, slot: u8): bool {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&slot));
        dapp_system::has_record<DappKey>(user_storage, key_tuple)
    }

    public fun ensure_has(user_storage: &UserStorage, slot: u8) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&slot));
        dapp_system::ensure_has_record<DappKey>(user_storage, key_tuple)
    }

    public fun ensure_has_not(user_storage: &UserStorage, slot: u8) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&slot));
        dapp_system::ensure_has_not_record<DappKey>(user_storage, key_tuple)
    }
  

    public(package) fun delete(user_storage: &mut UserStorage, slot: u8, ctx: &TxContext) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&slot));
        dapp_system::delete_record<DappKey>(dapp_key::new(), user_storage, key_tuple, vector[b"pet_id"], ctx);
    }

    public fun get(user_storage: &UserStorage, slot: u8): address {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&slot));
        let pet_id_raw = dapp_system::get_field<DappKey>(user_storage, key_tuple, b"pet_id");
        let mut pet_id_bcs = sui::bcs::new(pet_id_raw);
        let value = sui::bcs::peel_address(&mut pet_id_bcs);
        value
    }

    public(package) fun set(user_storage: &mut UserStorage, slot: u8, value: address, ctx: &mut TxContext) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&slot));
        let field_names = vector[b"pet_id"];
        let value_tuple = encode(value);
        dapp_system::set_record<DappKey>(dapp_key::new(), user_storage, key_tuple, field_names, value_tuple, OFFCHAIN, ctx);
    }

    public fun encode(value: address): vector<vector<u8>> {
        let mut value_tuple = vector::empty();
        value_tuple.push_back(to_bytes(&value));
        value_tuple
    }


    // ─── keys: mint (developer provides keys; framework ensures no duplicate) ─
    // Choosing the ID strategy (fresh address, counter, coordinate pack, etc.)
    // is intentionally left to the caller.
    public(package) fun mint(
        user_storage: &mut UserStorage,
        slot: u8, pet_id: address,
        ctx: &mut TxContext,
    ) {
        ensure_has_not(user_storage, slot);
        set(user_storage, slot, pet_id, ctx);
    }
}