// Copyright (c) Obelisk Labs, Inc.
// SPDX-License-Identifier: Apache-2.0

/* Autogenerated file. Do not edit manually. */

module harvest::pet_hatch {
    use sui::bcs::{to_bytes};
    use dubhe::dapp_service::UserStorage;
    use dubhe::dapp_system;
    use harvest::dapp_key;
    use harvest::dapp_key::DappKey;


    const TABLE_NAME: vector<u8> = b"pet_hatch";
    const OFFCHAIN: bool = false;

    public struct PetHatch has copy, drop, store {
        egg_type: u8,
        hatch_at: u64,
    }

    public fun new(egg_type: u8, hatch_at: u64): PetHatch {
        PetHatch {
            egg_type,
            hatch_at,
        }
    }

    public fun egg_type(self: &PetHatch): u8 {
        self.egg_type
    }

    public fun hatch_at(self: &PetHatch): u64 {
        self.hatch_at
    }

    public fun update_egg_type(self: &mut PetHatch, egg_type: u8) {
        self.egg_type = egg_type
    }

    public fun update_hatch_at(self: &mut PetHatch, hatch_at: u64) {
        self.hatch_at = hatch_at
    }

    public fun has(user_storage: &UserStorage): bool {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        dapp_system::has_record<DappKey>(user_storage, key_tuple)
    }

    public fun ensure_has(user_storage: &UserStorage) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        dapp_system::ensure_has_record<DappKey>(user_storage, key_tuple)
    }

    public fun ensure_has_not(user_storage: &UserStorage) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        dapp_system::ensure_has_not_record<DappKey>(user_storage, key_tuple)
    }
  

    public(package) fun delete(user_storage: &mut UserStorage, ctx: &TxContext) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        dapp_system::delete_record<DappKey>(dapp_key::new(), user_storage, key_tuple, vector[b"egg_type", b"hatch_at"], ctx);
    }

    public fun get_egg_type(user_storage: &UserStorage): u8 {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        let egg_type_raw = dapp_system::get_field<DappKey>(user_storage, key_tuple, b"egg_type");
        let mut egg_type_bcs = sui::bcs::new(egg_type_raw);
        let egg_type = sui::bcs::peel_u8(&mut egg_type_bcs);
        egg_type
    }

    public(package) fun set_egg_type(user_storage: &mut UserStorage, egg_type: u8, ctx: &mut TxContext) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        let value = to_bytes(&egg_type);
        dapp_system::set_field<DappKey>(dapp_key::new(), user_storage, key_tuple, b"egg_type", value, ctx);
    }

    public fun get_hatch_at(user_storage: &UserStorage): u64 {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        let hatch_at_raw = dapp_system::get_field<DappKey>(user_storage, key_tuple, b"hatch_at");
        let mut hatch_at_bcs = sui::bcs::new(hatch_at_raw);
        let hatch_at = sui::bcs::peel_u64(&mut hatch_at_bcs);
        hatch_at
    }

    public(package) fun set_hatch_at(user_storage: &mut UserStorage, hatch_at: u64, ctx: &mut TxContext) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        let value = to_bytes(&hatch_at);
        dapp_system::set_field<DappKey>(dapp_key::new(), user_storage, key_tuple, b"hatch_at", value, ctx);
    }

    public fun get(user_storage: &UserStorage): (u8, u64) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        let egg_type_raw = dapp_system::get_field<DappKey>(user_storage, key_tuple, b"egg_type");
        let mut egg_type_bcs = sui::bcs::new(egg_type_raw);
        let egg_type = sui::bcs::peel_u8(&mut egg_type_bcs);
        let hatch_at_raw = dapp_system::get_field<DappKey>(user_storage, key_tuple, b"hatch_at");
        let mut hatch_at_bcs = sui::bcs::new(hatch_at_raw);
        let hatch_at = sui::bcs::peel_u64(&mut hatch_at_bcs);
        (egg_type, hatch_at)
    }

    public(package) fun set(user_storage: &mut UserStorage, egg_type: u8, hatch_at: u64, ctx: &mut TxContext) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        let field_names = vector[b"egg_type", b"hatch_at"];
        let value_tuple = encode(egg_type, hatch_at);
        dapp_system::set_record<DappKey>(dapp_key::new(), user_storage, key_tuple, field_names, value_tuple, OFFCHAIN, ctx);
    }

    public fun get_struct(user_storage: &UserStorage): PetHatch {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        let egg_type_raw = dapp_system::get_field<DappKey>(user_storage, key_tuple, b"egg_type");
        let mut egg_type_bcs = sui::bcs::new(egg_type_raw);
        let egg_type = sui::bcs::peel_u8(&mut egg_type_bcs);
        let hatch_at_raw = dapp_system::get_field<DappKey>(user_storage, key_tuple, b"hatch_at");
        let mut hatch_at_bcs = sui::bcs::new(hatch_at_raw);
        let hatch_at = sui::bcs::peel_u64(&mut hatch_at_bcs);
        PetHatch { egg_type, hatch_at }
    }

    public(package) fun set_struct(user_storage: &mut UserStorage, pet_hatch: PetHatch, ctx: &mut TxContext) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        let field_names = vector[b"egg_type", b"hatch_at"];
        let value_tuple = encode_struct(pet_hatch);
        dapp_system::set_record<DappKey>(dapp_key::new(), user_storage, key_tuple, field_names, value_tuple, OFFCHAIN, ctx);
    }

    public fun encode(egg_type: u8, hatch_at: u64): vector<vector<u8>> {
        let mut value_tuple = vector::empty();
        value_tuple.push_back(to_bytes(&egg_type));
        value_tuple.push_back(to_bytes(&hatch_at));
        value_tuple
    }

    public fun encode_struct(pet_hatch: PetHatch): vector<vector<u8>> {
        encode(pet_hatch.egg_type, pet_hatch.hatch_at)
    }

    public fun decode(data: vector<u8>): PetHatch {
        let mut bcs_type = sui::bcs::new(data);
        let egg_type = sui::bcs::peel_u8(&mut bcs_type);
        let hatch_at = sui::bcs::peel_u64(&mut bcs_type);
        PetHatch {
            egg_type,
            hatch_at,
        }
    }
}