// Copyright (c) Obelisk Labs, Inc.
// SPDX-License-Identifier: Apache-2.0

/* Autogenerated file. Do not edit manually. */

module harvest::profile {
    use sui::bcs::{to_bytes};
    use dubhe::dapp_service::UserStorage;
    use dubhe::dapp_system;
    use harvest::dapp_key;
    use harvest::dapp_key::DappKey;


    const TABLE_NAME: vector<u8> = b"profile";
    const OFFCHAIN: bool = false;

    public struct Profile has copy, drop, store {
        total_earned: u64,
        plots_owned: u8,
    }

    public fun new(total_earned: u64, plots_owned: u8): Profile {
        Profile {
            total_earned,
            plots_owned,
        }
    }

    public fun total_earned(self: &Profile): u64 {
        self.total_earned
    }

    public fun plots_owned(self: &Profile): u8 {
        self.plots_owned
    }

    public fun update_total_earned(self: &mut Profile, total_earned: u64) {
        self.total_earned = total_earned
    }

    public fun update_plots_owned(self: &mut Profile, plots_owned: u8) {
        self.plots_owned = plots_owned
    }

    public fun has(user_storage: &UserStorage): bool {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        dapp_system::has_record<DappKey>(user_storage, key_tuple)
    }

    public fun ensure_has(user_storage: &UserStorage) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        dapp_system::ensure_has_record<DappKey>(user_storage, key_tuple)
    }

    public fun ensure_has_not(user_storage: &UserStorage) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        dapp_system::ensure_has_not_record<DappKey>(user_storage, key_tuple)
    }
  

    public(package) fun delete(user_storage: &mut UserStorage, ctx: &TxContext) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        dapp_system::delete_record<DappKey>(dapp_key::new(), user_storage, key_tuple, vector[b"total_earned", b"plots_owned"], ctx);
    }

    public fun get_total_earned(user_storage: &UserStorage): u64 {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        let total_earned_raw = dapp_system::get_field<DappKey>(user_storage, key_tuple, b"total_earned");
        let mut total_earned_bcs = sui::bcs::new(total_earned_raw);
        let total_earned = sui::bcs::peel_u64(&mut total_earned_bcs);
        total_earned
    }

    public(package) fun set_total_earned(user_storage: &mut UserStorage, total_earned: u64, ctx: &mut TxContext) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        let value = to_bytes(&total_earned);
        dapp_system::set_field<DappKey>(dapp_key::new(), user_storage, key_tuple, b"total_earned", value, ctx);
    }

    public fun get_plots_owned(user_storage: &UserStorage): u8 {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        let plots_owned_raw = dapp_system::get_field<DappKey>(user_storage, key_tuple, b"plots_owned");
        let mut plots_owned_bcs = sui::bcs::new(plots_owned_raw);
        let plots_owned = sui::bcs::peel_u8(&mut plots_owned_bcs);
        plots_owned
    }

    public(package) fun set_plots_owned(user_storage: &mut UserStorage, plots_owned: u8, ctx: &mut TxContext) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        let value = to_bytes(&plots_owned);
        dapp_system::set_field<DappKey>(dapp_key::new(), user_storage, key_tuple, b"plots_owned", value, ctx);
    }

    public fun get(user_storage: &UserStorage): (u64, u8) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        let total_earned_raw = dapp_system::get_field<DappKey>(user_storage, key_tuple, b"total_earned");
        let mut total_earned_bcs = sui::bcs::new(total_earned_raw);
        let total_earned = sui::bcs::peel_u64(&mut total_earned_bcs);
        let plots_owned_raw = dapp_system::get_field<DappKey>(user_storage, key_tuple, b"plots_owned");
        let mut plots_owned_bcs = sui::bcs::new(plots_owned_raw);
        let plots_owned = sui::bcs::peel_u8(&mut plots_owned_bcs);
        (total_earned, plots_owned)
    }

    public(package) fun set(user_storage: &mut UserStorage, total_earned: u64, plots_owned: u8, ctx: &mut TxContext) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        let field_names = vector[b"total_earned", b"plots_owned"];
        let value_tuple = encode(total_earned, plots_owned);
        dapp_system::set_record<DappKey>(dapp_key::new(), user_storage, key_tuple, field_names, value_tuple, OFFCHAIN, ctx);
    }

    public fun get_struct(user_storage: &UserStorage): Profile {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        let total_earned_raw = dapp_system::get_field<DappKey>(user_storage, key_tuple, b"total_earned");
        let mut total_earned_bcs = sui::bcs::new(total_earned_raw);
        let total_earned = sui::bcs::peel_u64(&mut total_earned_bcs);
        let plots_owned_raw = dapp_system::get_field<DappKey>(user_storage, key_tuple, b"plots_owned");
        let mut plots_owned_bcs = sui::bcs::new(plots_owned_raw);
        let plots_owned = sui::bcs::peel_u8(&mut plots_owned_bcs);
        Profile { total_earned, plots_owned }
    }

    public(package) fun set_struct(user_storage: &mut UserStorage, profile: Profile, ctx: &mut TxContext) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        let field_names = vector[b"total_earned", b"plots_owned"];
        let value_tuple = encode_struct(profile);
        dapp_system::set_record<DappKey>(dapp_key::new(), user_storage, key_tuple, field_names, value_tuple, OFFCHAIN, ctx);
    }

    public fun encode(total_earned: u64, plots_owned: u8): vector<vector<u8>> {
        let mut value_tuple = vector::empty();
        value_tuple.push_back(to_bytes(&total_earned));
        value_tuple.push_back(to_bytes(&plots_owned));
        value_tuple
    }

    public fun encode_struct(profile: Profile): vector<vector<u8>> {
        encode(profile.total_earned, profile.plots_owned)
    }

    public fun decode(data: vector<u8>): Profile {
        let mut bcs_type = sui::bcs::new(data);
        let total_earned = sui::bcs::peel_u64(&mut bcs_type);
        let plots_owned = sui::bcs::peel_u8(&mut bcs_type);
        Profile {
            total_earned,
            plots_owned,
        }
    }
}