// Copyright (c) Obelisk Labs, Inc.
// SPDX-License-Identifier: Apache-2.0

/* Autogenerated file. Do not edit manually. */

module harvest::season_config {
    use sui::bcs::{to_bytes};
    use dubhe::dapp_service::DappStorage;
    use dubhe::dapp_system;
    use harvest::dapp_key;
    use harvest::dapp_key::DappKey;


    const TABLE_NAME: vector<u8> = b"season_config";
    const OFFCHAIN: bool = false;

    public struct SeasonConfig has copy, drop, store {
        season_id: u8,
        end_ms: u64,
        bonus_crop: u8,
    }

    public fun new(season_id: u8, end_ms: u64, bonus_crop: u8): SeasonConfig {
        SeasonConfig {
            season_id,
            end_ms,
            bonus_crop,
        }
    }

    public fun season_id(self: &SeasonConfig): u8 {
        self.season_id
    }

    public fun end_ms(self: &SeasonConfig): u64 {
        self.end_ms
    }

    public fun bonus_crop(self: &SeasonConfig): u8 {
        self.bonus_crop
    }

    public fun update_season_id(self: &mut SeasonConfig, season_id: u8) {
        self.season_id = season_id
    }

    public fun update_end_ms(self: &mut SeasonConfig, end_ms: u64) {
        self.end_ms = end_ms
    }

    public fun update_bonus_crop(self: &mut SeasonConfig, bonus_crop: u8) {
        self.bonus_crop = bonus_crop
    }

    public fun has(dapp_storage: &DappStorage): bool {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        dapp_system::has_global_record<DappKey>(dapp_storage, key_tuple)
    }

    public fun ensure_has(dapp_storage: &DappStorage) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        dapp_system::ensure_has_global_record<DappKey>(dapp_storage, key_tuple)
    }

    public fun ensure_has_not(dapp_storage: &DappStorage) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        dapp_system::ensure_has_not_global_record<DappKey>(dapp_storage, key_tuple)
    }
  

    public(package) fun delete(dapp_storage: &mut DappStorage) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        dapp_system::delete_global_record<DappKey>(dapp_key::new(), dapp_storage, key_tuple, vector[b"season_id", b"end_ms", b"bonus_crop"]);
    }

    public fun get_season_id(dapp_storage: &DappStorage): u8 {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        let season_id_raw = dapp_system::get_global_field<DappKey>(dapp_storage, key_tuple, b"season_id");
        let mut season_id_bcs = sui::bcs::new(season_id_raw);
        let season_id = sui::bcs::peel_u8(&mut season_id_bcs);
        season_id
    }

    public(package) fun set_season_id(dapp_storage: &mut DappStorage, season_id: u8) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        let value = to_bytes(&season_id);
        dapp_system::set_global_field<DappKey>(dapp_key::new(), dapp_storage, key_tuple, b"season_id", value);
    }

    public fun get_end_ms(dapp_storage: &DappStorage): u64 {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        let end_ms_raw = dapp_system::get_global_field<DappKey>(dapp_storage, key_tuple, b"end_ms");
        let mut end_ms_bcs = sui::bcs::new(end_ms_raw);
        let end_ms = sui::bcs::peel_u64(&mut end_ms_bcs);
        end_ms
    }

    public(package) fun set_end_ms(dapp_storage: &mut DappStorage, end_ms: u64) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        let value = to_bytes(&end_ms);
        dapp_system::set_global_field<DappKey>(dapp_key::new(), dapp_storage, key_tuple, b"end_ms", value);
    }

    public fun get_bonus_crop(dapp_storage: &DappStorage): u8 {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        let bonus_crop_raw = dapp_system::get_global_field<DappKey>(dapp_storage, key_tuple, b"bonus_crop");
        let mut bonus_crop_bcs = sui::bcs::new(bonus_crop_raw);
        let bonus_crop = sui::bcs::peel_u8(&mut bonus_crop_bcs);
        bonus_crop
    }

    public(package) fun set_bonus_crop(dapp_storage: &mut DappStorage, bonus_crop: u8) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        let value = to_bytes(&bonus_crop);
        dapp_system::set_global_field<DappKey>(dapp_key::new(), dapp_storage, key_tuple, b"bonus_crop", value);
    }

    public fun get(dapp_storage: &DappStorage): (u8, u64, u8) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        let season_id_raw = dapp_system::get_global_field<DappKey>(dapp_storage, key_tuple, b"season_id");
        let mut season_id_bcs = sui::bcs::new(season_id_raw);
        let season_id = sui::bcs::peel_u8(&mut season_id_bcs);
        let end_ms_raw = dapp_system::get_global_field<DappKey>(dapp_storage, key_tuple, b"end_ms");
        let mut end_ms_bcs = sui::bcs::new(end_ms_raw);
        let end_ms = sui::bcs::peel_u64(&mut end_ms_bcs);
        let bonus_crop_raw = dapp_system::get_global_field<DappKey>(dapp_storage, key_tuple, b"bonus_crop");
        let mut bonus_crop_bcs = sui::bcs::new(bonus_crop_raw);
        let bonus_crop = sui::bcs::peel_u8(&mut bonus_crop_bcs);
        (season_id, end_ms, bonus_crop)
    }

    public(package) fun set(dapp_storage: &mut DappStorage, season_id: u8, end_ms: u64, bonus_crop: u8) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        let field_names = vector[b"season_id", b"end_ms", b"bonus_crop"];
        let value_tuple = encode(season_id, end_ms, bonus_crop);
        dapp_system::set_global_record<DappKey>(dapp_key::new(), dapp_storage, key_tuple, field_names, value_tuple, OFFCHAIN);
    }

    public fun get_struct(dapp_storage: &DappStorage): SeasonConfig {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        let season_id_raw = dapp_system::get_global_field<DappKey>(dapp_storage, key_tuple, b"season_id");
        let mut season_id_bcs = sui::bcs::new(season_id_raw);
        let season_id = sui::bcs::peel_u8(&mut season_id_bcs);
        let end_ms_raw = dapp_system::get_global_field<DappKey>(dapp_storage, key_tuple, b"end_ms");
        let mut end_ms_bcs = sui::bcs::new(end_ms_raw);
        let end_ms = sui::bcs::peel_u64(&mut end_ms_bcs);
        let bonus_crop_raw = dapp_system::get_global_field<DappKey>(dapp_storage, key_tuple, b"bonus_crop");
        let mut bonus_crop_bcs = sui::bcs::new(bonus_crop_raw);
        let bonus_crop = sui::bcs::peel_u8(&mut bonus_crop_bcs);
        SeasonConfig { season_id, end_ms, bonus_crop }
    }

    public(package) fun set_struct(dapp_storage: &mut DappStorage, season_config: SeasonConfig) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        let field_names = vector[b"season_id", b"end_ms", b"bonus_crop"];
        let value_tuple = encode_struct(season_config);
        dapp_system::set_global_record<DappKey>(dapp_key::new(), dapp_storage, key_tuple, field_names, value_tuple, OFFCHAIN);
    }

    public fun encode(season_id: u8, end_ms: u64, bonus_crop: u8): vector<vector<u8>> {
        let mut value_tuple = vector::empty();
        value_tuple.push_back(to_bytes(&season_id));
        value_tuple.push_back(to_bytes(&end_ms));
        value_tuple.push_back(to_bytes(&bonus_crop));
        value_tuple
    }

    public fun encode_struct(season_config: SeasonConfig): vector<vector<u8>> {
        encode(season_config.season_id, season_config.end_ms, season_config.bonus_crop)
    }

    public fun decode(data: vector<u8>): SeasonConfig {
        let mut bcs_type = sui::bcs::new(data);
        let season_id = sui::bcs::peel_u8(&mut bcs_type);
        let end_ms = sui::bcs::peel_u64(&mut bcs_type);
        let bonus_crop = sui::bcs::peel_u8(&mut bcs_type);
        SeasonConfig {
            season_id,
            end_ms,
            bonus_crop,
        }
    }
}