// Copyright (c) Obelisk Labs, Inc.
// SPDX-License-Identifier: Apache-2.0

/* Autogenerated file. Do not edit manually. */

module harvest::shop_config {
    use sui::bcs::{to_bytes};
    use dubhe::dapp_service::DappStorage;
    use dubhe::dapp_system;
    use harvest::dapp_key;
    use harvest::dapp_key::DappKey;


    const TABLE_NAME: vector<u8> = b"shop_config";
    const OFFCHAIN: bool = false;

    public struct ShopConfig has copy, drop, store {
        wheat_seed_price: u64,
        corn_seed_price: u64,
        carrot_seed_price: u64,
        pumpkin_seed_price: u64,
        extra_plot_price: u64,
    }

    public fun new(wheat_seed_price: u64, corn_seed_price: u64, carrot_seed_price: u64, pumpkin_seed_price: u64, extra_plot_price: u64): ShopConfig {
        ShopConfig {
            wheat_seed_price,
            corn_seed_price,
            carrot_seed_price,
            pumpkin_seed_price,
            extra_plot_price,
        }
    }

    public fun wheat_seed_price(self: &ShopConfig): u64 {
        self.wheat_seed_price
    }

    public fun corn_seed_price(self: &ShopConfig): u64 {
        self.corn_seed_price
    }

    public fun carrot_seed_price(self: &ShopConfig): u64 {
        self.carrot_seed_price
    }

    public fun pumpkin_seed_price(self: &ShopConfig): u64 {
        self.pumpkin_seed_price
    }

    public fun extra_plot_price(self: &ShopConfig): u64 {
        self.extra_plot_price
    }

    public fun update_wheat_seed_price(self: &mut ShopConfig, wheat_seed_price: u64) {
        self.wheat_seed_price = wheat_seed_price
    }

    public fun update_corn_seed_price(self: &mut ShopConfig, corn_seed_price: u64) {
        self.corn_seed_price = corn_seed_price
    }

    public fun update_carrot_seed_price(self: &mut ShopConfig, carrot_seed_price: u64) {
        self.carrot_seed_price = carrot_seed_price
    }

    public fun update_pumpkin_seed_price(self: &mut ShopConfig, pumpkin_seed_price: u64) {
        self.pumpkin_seed_price = pumpkin_seed_price
    }

    public fun update_extra_plot_price(self: &mut ShopConfig, extra_plot_price: u64) {
        self.extra_plot_price = extra_plot_price
    }

    public fun has(dapp_storage: &DappStorage): bool {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        dapp_system::has_global_record<DappKey>(dapp_storage, key_tuple)
    }

    public fun ensure_has(dapp_storage: &DappStorage) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        dapp_system::ensure_has_global_record<DappKey>(dapp_storage, key_tuple)
    }

    public fun ensure_has_not(dapp_storage: &DappStorage) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        dapp_system::ensure_has_not_global_record<DappKey>(dapp_storage, key_tuple)
    }
  

    public(package) fun delete(dapp_storage: &mut DappStorage) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        dapp_system::delete_global_record<DappKey>(dapp_key::new(), dapp_storage, key_tuple, vector[b"wheat_seed_price", b"corn_seed_price", b"carrot_seed_price", b"pumpkin_seed_price", b"extra_plot_price"]);
    }

    public fun get_wheat_seed_price(dapp_storage: &DappStorage): u64 {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        let wheat_seed_price_raw = dapp_system::get_global_field<DappKey>(dapp_storage, key_tuple, b"wheat_seed_price");
        let mut wheat_seed_price_bcs = sui::bcs::new(wheat_seed_price_raw);
        let wheat_seed_price = sui::bcs::peel_u64(&mut wheat_seed_price_bcs);
        wheat_seed_price
    }

    public(package) fun set_wheat_seed_price(dapp_storage: &mut DappStorage, wheat_seed_price: u64) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        let value = to_bytes(&wheat_seed_price);
        dapp_system::set_global_field<DappKey>(dapp_key::new(), dapp_storage, key_tuple, b"wheat_seed_price", value);
    }

    public fun get_corn_seed_price(dapp_storage: &DappStorage): u64 {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        let corn_seed_price_raw = dapp_system::get_global_field<DappKey>(dapp_storage, key_tuple, b"corn_seed_price");
        let mut corn_seed_price_bcs = sui::bcs::new(corn_seed_price_raw);
        let corn_seed_price = sui::bcs::peel_u64(&mut corn_seed_price_bcs);
        corn_seed_price
    }

    public(package) fun set_corn_seed_price(dapp_storage: &mut DappStorage, corn_seed_price: u64) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        let value = to_bytes(&corn_seed_price);
        dapp_system::set_global_field<DappKey>(dapp_key::new(), dapp_storage, key_tuple, b"corn_seed_price", value);
    }

    public fun get_carrot_seed_price(dapp_storage: &DappStorage): u64 {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        let carrot_seed_price_raw = dapp_system::get_global_field<DappKey>(dapp_storage, key_tuple, b"carrot_seed_price");
        let mut carrot_seed_price_bcs = sui::bcs::new(carrot_seed_price_raw);
        let carrot_seed_price = sui::bcs::peel_u64(&mut carrot_seed_price_bcs);
        carrot_seed_price
    }

    public(package) fun set_carrot_seed_price(dapp_storage: &mut DappStorage, carrot_seed_price: u64) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        let value = to_bytes(&carrot_seed_price);
        dapp_system::set_global_field<DappKey>(dapp_key::new(), dapp_storage, key_tuple, b"carrot_seed_price", value);
    }

    public fun get_pumpkin_seed_price(dapp_storage: &DappStorage): u64 {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        let pumpkin_seed_price_raw = dapp_system::get_global_field<DappKey>(dapp_storage, key_tuple, b"pumpkin_seed_price");
        let mut pumpkin_seed_price_bcs = sui::bcs::new(pumpkin_seed_price_raw);
        let pumpkin_seed_price = sui::bcs::peel_u64(&mut pumpkin_seed_price_bcs);
        pumpkin_seed_price
    }

    public(package) fun set_pumpkin_seed_price(dapp_storage: &mut DappStorage, pumpkin_seed_price: u64) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        let value = to_bytes(&pumpkin_seed_price);
        dapp_system::set_global_field<DappKey>(dapp_key::new(), dapp_storage, key_tuple, b"pumpkin_seed_price", value);
    }

    public fun get_extra_plot_price(dapp_storage: &DappStorage): u64 {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        let extra_plot_price_raw = dapp_system::get_global_field<DappKey>(dapp_storage, key_tuple, b"extra_plot_price");
        let mut extra_plot_price_bcs = sui::bcs::new(extra_plot_price_raw);
        let extra_plot_price = sui::bcs::peel_u64(&mut extra_plot_price_bcs);
        extra_plot_price
    }

    public(package) fun set_extra_plot_price(dapp_storage: &mut DappStorage, extra_plot_price: u64) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        let value = to_bytes(&extra_plot_price);
        dapp_system::set_global_field<DappKey>(dapp_key::new(), dapp_storage, key_tuple, b"extra_plot_price", value);
    }

    public fun get(dapp_storage: &DappStorage): (u64, u64, u64, u64, u64) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        let wheat_seed_price_raw = dapp_system::get_global_field<DappKey>(dapp_storage, key_tuple, b"wheat_seed_price");
        let mut wheat_seed_price_bcs = sui::bcs::new(wheat_seed_price_raw);
        let wheat_seed_price = sui::bcs::peel_u64(&mut wheat_seed_price_bcs);
        let corn_seed_price_raw = dapp_system::get_global_field<DappKey>(dapp_storage, key_tuple, b"corn_seed_price");
        let mut corn_seed_price_bcs = sui::bcs::new(corn_seed_price_raw);
        let corn_seed_price = sui::bcs::peel_u64(&mut corn_seed_price_bcs);
        let carrot_seed_price_raw = dapp_system::get_global_field<DappKey>(dapp_storage, key_tuple, b"carrot_seed_price");
        let mut carrot_seed_price_bcs = sui::bcs::new(carrot_seed_price_raw);
        let carrot_seed_price = sui::bcs::peel_u64(&mut carrot_seed_price_bcs);
        let pumpkin_seed_price_raw = dapp_system::get_global_field<DappKey>(dapp_storage, key_tuple, b"pumpkin_seed_price");
        let mut pumpkin_seed_price_bcs = sui::bcs::new(pumpkin_seed_price_raw);
        let pumpkin_seed_price = sui::bcs::peel_u64(&mut pumpkin_seed_price_bcs);
        let extra_plot_price_raw = dapp_system::get_global_field<DappKey>(dapp_storage, key_tuple, b"extra_plot_price");
        let mut extra_plot_price_bcs = sui::bcs::new(extra_plot_price_raw);
        let extra_plot_price = sui::bcs::peel_u64(&mut extra_plot_price_bcs);
        (wheat_seed_price, corn_seed_price, carrot_seed_price, pumpkin_seed_price, extra_plot_price)
    }

    public(package) fun set(dapp_storage: &mut DappStorage, wheat_seed_price: u64, corn_seed_price: u64, carrot_seed_price: u64, pumpkin_seed_price: u64, extra_plot_price: u64) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        let field_names = vector[b"wheat_seed_price", b"corn_seed_price", b"carrot_seed_price", b"pumpkin_seed_price", b"extra_plot_price"];
        let value_tuple = encode(wheat_seed_price, corn_seed_price, carrot_seed_price, pumpkin_seed_price, extra_plot_price);
        dapp_system::set_global_record<DappKey>(dapp_key::new(), dapp_storage, key_tuple, field_names, value_tuple, OFFCHAIN);
    }

    public fun get_struct(dapp_storage: &DappStorage): ShopConfig {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        let wheat_seed_price_raw = dapp_system::get_global_field<DappKey>(dapp_storage, key_tuple, b"wheat_seed_price");
        let mut wheat_seed_price_bcs = sui::bcs::new(wheat_seed_price_raw);
        let wheat_seed_price = sui::bcs::peel_u64(&mut wheat_seed_price_bcs);
        let corn_seed_price_raw = dapp_system::get_global_field<DappKey>(dapp_storage, key_tuple, b"corn_seed_price");
        let mut corn_seed_price_bcs = sui::bcs::new(corn_seed_price_raw);
        let corn_seed_price = sui::bcs::peel_u64(&mut corn_seed_price_bcs);
        let carrot_seed_price_raw = dapp_system::get_global_field<DappKey>(dapp_storage, key_tuple, b"carrot_seed_price");
        let mut carrot_seed_price_bcs = sui::bcs::new(carrot_seed_price_raw);
        let carrot_seed_price = sui::bcs::peel_u64(&mut carrot_seed_price_bcs);
        let pumpkin_seed_price_raw = dapp_system::get_global_field<DappKey>(dapp_storage, key_tuple, b"pumpkin_seed_price");
        let mut pumpkin_seed_price_bcs = sui::bcs::new(pumpkin_seed_price_raw);
        let pumpkin_seed_price = sui::bcs::peel_u64(&mut pumpkin_seed_price_bcs);
        let extra_plot_price_raw = dapp_system::get_global_field<DappKey>(dapp_storage, key_tuple, b"extra_plot_price");
        let mut extra_plot_price_bcs = sui::bcs::new(extra_plot_price_raw);
        let extra_plot_price = sui::bcs::peel_u64(&mut extra_plot_price_bcs);
        ShopConfig { wheat_seed_price, corn_seed_price, carrot_seed_price, pumpkin_seed_price, extra_plot_price }
    }

    public(package) fun set_struct(dapp_storage: &mut DappStorage, shop_config: ShopConfig) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        let field_names = vector[b"wheat_seed_price", b"corn_seed_price", b"carrot_seed_price", b"pumpkin_seed_price", b"extra_plot_price"];
        let value_tuple = encode_struct(shop_config);
        dapp_system::set_global_record<DappKey>(dapp_key::new(), dapp_storage, key_tuple, field_names, value_tuple, OFFCHAIN);
    }

    public fun encode(wheat_seed_price: u64, corn_seed_price: u64, carrot_seed_price: u64, pumpkin_seed_price: u64, extra_plot_price: u64): vector<vector<u8>> {
        let mut value_tuple = vector::empty();
        value_tuple.push_back(to_bytes(&wheat_seed_price));
        value_tuple.push_back(to_bytes(&corn_seed_price));
        value_tuple.push_back(to_bytes(&carrot_seed_price));
        value_tuple.push_back(to_bytes(&pumpkin_seed_price));
        value_tuple.push_back(to_bytes(&extra_plot_price));
        value_tuple
    }

    public fun encode_struct(shop_config: ShopConfig): vector<vector<u8>> {
        encode(shop_config.wheat_seed_price, shop_config.corn_seed_price, shop_config.carrot_seed_price, shop_config.pumpkin_seed_price, shop_config.extra_plot_price)
    }

    public fun decode(data: vector<u8>): ShopConfig {
        let mut bcs_type = sui::bcs::new(data);
        let wheat_seed_price = sui::bcs::peel_u64(&mut bcs_type);
        let corn_seed_price = sui::bcs::peel_u64(&mut bcs_type);
        let carrot_seed_price = sui::bcs::peel_u64(&mut bcs_type);
        let pumpkin_seed_price = sui::bcs::peel_u64(&mut bcs_type);
        let extra_plot_price = sui::bcs::peel_u64(&mut bcs_type);
        ShopConfig {
            wheat_seed_price,
            corn_seed_price,
            carrot_seed_price,
            pumpkin_seed_price,
            extra_plot_price,
        }
    }
}