// Copyright (c) Obelisk Labs, Inc.
// SPDX-License-Identifier: Apache-2.0

/* Autogenerated file. Do not edit manually. */

module harvest::trophy {
    use sui::bcs::{to_bytes};
    use dubhe::dapp_service::{UserStorage, DappStorage};
    use dubhe::dapp_system;
    use harvest::dapp_key;
    use harvest::dapp_key::DappKey;


    const TABLE_NAME: vector<u8> = b"trophy";
    const OFFCHAIN: bool = false;

    public struct Trophy has copy, drop, store {
        rank: u32,
        total_earned: u64,
    }

    public fun new(rank: u32, total_earned: u64): Trophy {
        Trophy {
            rank,
            total_earned,
        }
    }

    public fun rank(self: &Trophy): u32 {
        self.rank
    }

    public fun total_earned(self: &Trophy): u64 {
        self.total_earned
    }

    public fun update_rank(self: &mut Trophy, rank: u32) {
        self.rank = rank
    }

    public fun update_total_earned(self: &mut Trophy, total_earned: u64) {
        self.total_earned = total_earned
    }

    public fun has(user_storage: &UserStorage, season: u8): bool {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&season));
        dapp_system::has_record<DappKey>(user_storage, key_tuple)
    }

    public fun ensure_has(user_storage: &UserStorage, season: u8) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&season));
        dapp_system::ensure_has_record<DappKey>(user_storage, key_tuple)
    }

    public fun ensure_has_not(user_storage: &UserStorage, season: u8) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&season));
        dapp_system::ensure_has_not_record<DappKey>(user_storage, key_tuple)
    }
  

    public(package) fun delete(user_storage: &mut UserStorage, season: u8, ctx: &TxContext) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&season));
        dapp_system::delete_record<DappKey>(dapp_key::new(), user_storage, key_tuple, vector[b"rank", b"total_earned"], ctx);
    }

    public fun get_rank(user_storage: &UserStorage, season: u8): u32 {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&season));
        let rank_raw = dapp_system::get_field<DappKey>(user_storage, key_tuple, b"rank");
        let mut rank_bcs = sui::bcs::new(rank_raw);
        let rank = sui::bcs::peel_u32(&mut rank_bcs);
        rank
    }

    public(package) fun set_rank(user_storage: &mut UserStorage, season: u8, rank: u32, ctx: &mut TxContext) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&season));
        let value = to_bytes(&rank);
        dapp_system::set_field<DappKey>(dapp_key::new(), user_storage, key_tuple, b"rank", value, ctx);
    }

    public fun get_total_earned(user_storage: &UserStorage, season: u8): u64 {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&season));
        let total_earned_raw = dapp_system::get_field<DappKey>(user_storage, key_tuple, b"total_earned");
        let mut total_earned_bcs = sui::bcs::new(total_earned_raw);
        let total_earned = sui::bcs::peel_u64(&mut total_earned_bcs);
        total_earned
    }

    public(package) fun set_total_earned(user_storage: &mut UserStorage, season: u8, total_earned: u64, ctx: &mut TxContext) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&season));
        let value = to_bytes(&total_earned);
        dapp_system::set_field<DappKey>(dapp_key::new(), user_storage, key_tuple, b"total_earned", value, ctx);
    }

    public fun get(user_storage: &UserStorage, season: u8): (u32, u64) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&season));
        let rank_raw = dapp_system::get_field<DappKey>(user_storage, key_tuple, b"rank");
        let mut rank_bcs = sui::bcs::new(rank_raw);
        let rank = sui::bcs::peel_u32(&mut rank_bcs);
        let total_earned_raw = dapp_system::get_field<DappKey>(user_storage, key_tuple, b"total_earned");
        let mut total_earned_bcs = sui::bcs::new(total_earned_raw);
        let total_earned = sui::bcs::peel_u64(&mut total_earned_bcs);
        (rank, total_earned)
    }

    public(package) fun set(user_storage: &mut UserStorage, season: u8, rank: u32, total_earned: u64, ctx: &mut TxContext) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&season));
        let field_names = vector[b"rank", b"total_earned"];
        let value_tuple = encode(rank, total_earned);
        dapp_system::set_record<DappKey>(dapp_key::new(), user_storage, key_tuple, field_names, value_tuple, OFFCHAIN, ctx);
    }

    public fun get_struct(user_storage: &UserStorage, season: u8): Trophy {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&season));
        let rank_raw = dapp_system::get_field<DappKey>(user_storage, key_tuple, b"rank");
        let mut rank_bcs = sui::bcs::new(rank_raw);
        let rank = sui::bcs::peel_u32(&mut rank_bcs);
        let total_earned_raw = dapp_system::get_field<DappKey>(user_storage, key_tuple, b"total_earned");
        let mut total_earned_bcs = sui::bcs::new(total_earned_raw);
        let total_earned = sui::bcs::peel_u64(&mut total_earned_bcs);
        Trophy { rank, total_earned }
    }

    public(package) fun set_struct(user_storage: &mut UserStorage, season: u8, trophy: Trophy, ctx: &mut TxContext) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&season));
        let field_names = vector[b"rank", b"total_earned"];
        let value_tuple = encode_struct(trophy);
        dapp_system::set_record<DappKey>(dapp_key::new(), user_storage, key_tuple, field_names, value_tuple, OFFCHAIN, ctx);
    }

    public fun encode(rank: u32, total_earned: u64): vector<vector<u8>> {
        let mut value_tuple = vector::empty();
        value_tuple.push_back(to_bytes(&rank));
        value_tuple.push_back(to_bytes(&total_earned));
        value_tuple
    }

    public fun encode_struct(trophy: Trophy): vector<vector<u8>> {
        encode(trophy.rank, trophy.total_earned)
    }

    public fun decode(data: vector<u8>): Trophy {
        let mut bcs_type = sui::bcs::new(data);
        let rank = sui::bcs::peel_u32(&mut bcs_type);
        let total_earned = sui::bcs::peel_u64(&mut bcs_type);
        Trophy {
            rank,
            total_earned,
        }
    }


    // ─── keys: mint (developer provides keys; framework ensures no duplicate) ─
    // Choosing the ID strategy (fresh address, counter, coordinate pack, etc.)
    // is intentionally left to the caller.
    public(package) fun mint(
        user_storage: &mut UserStorage,
        season: u8, rank: u32, total_earned: u64,
        ctx: &mut TxContext,
    ) {
        ensure_has_not(user_storage, season);
        set(user_storage, season, rank, total_earned, ctx);
    }

    // ─── listable: market protocol (keyed) ──────────────────────────────
    // Package-level helpers: call these from your system functions.
    // Add pause checks, access control, and custom logic there.
    public(package) fun list<CoinType>(
        user_storage: &mut UserStorage,
        season:   u8,
        price:        u64,
        listed_until: std::option::Option<u64>,
        ctx:          &mut TxContext,
    ) {
        let mut record_key = vector::empty();
        record_key.push_back(TABLE_NAME);
        record_key.push_back(sui::bcs::to_bytes(&season));
        dubhe::dapp_system::take_record<DappKey, CoinType>(
            dapp_key::new(),
            user_storage,
            b"trophy",
            record_key,
            vector[b"rank", b"total_earned"],
            price,
            listed_until,
            ctx,
        );
    }

    public(package) fun buy<CoinType>(
        dh:            &dubhe::dapp_service::DappHub,
        dapp_storage:  &mut DappStorage,
        listing:       dubhe::dapp_service::Listing<CoinType>,
        user_storage:  &mut UserStorage,
        payment:       sui::coin::Coin<CoinType>,
        ctx:           &mut TxContext,
    ): sui::coin::Coin<CoinType> {
        dubhe::dapp_system::buy_record<DappKey, CoinType>(
            dapp_key::new(), dh, dapp_storage, listing, user_storage, payment, ctx
        )
    }

    public(package) fun cancel_listing<CoinType>(
        listing:      dubhe::dapp_service::Listing<CoinType>,
        user_storage: &mut UserStorage,
        ctx:          &TxContext,
    ) {
        dubhe::dapp_system::restore_record<DappKey, CoinType>(
            dapp_key::new(), listing, user_storage, ctx
        );
    }

    public(package) fun expire_listing<CoinType>(
        listing:      dubhe::dapp_service::Listing<CoinType>,
        user_storage: &mut UserStorage,
        ctx:          &TxContext,
    ) {
        dubhe::dapp_system::expire_listing<DappKey, CoinType>(
            dapp_key::new(), listing, user_storage, ctx
        );
    }
}