// Copyright (c) Obelisk Labs, Inc.
// SPDX-License-Identifier: Apache-2.0

/* Autogenerated file. Do not edit manually. */

module harvest::error {
    #[error]
    const EAlreadyRegistered: vector<u8> = b"Player already registered";
    public fun already_registered(condition: bool) { assert!(condition, EAlreadyRegistered) }

    #[error]
    const ENotRegistered: vector<u8> = b"Player not registered";
    public fun not_registered(condition: bool) { assert!(condition, ENotRegistered) }

    #[error]
    const EPlotNotFound: vector<u8> = b"Farm plot not found";
    public fun plot_not_found(condition: bool) { assert!(condition, EPlotNotFound) }

    #[error]
    const EPlotAlreadyPlanted: vector<u8> = b"Farm plot already has a crop growing";
    public fun plot_already_planted(condition: bool) { assert!(condition, EPlotAlreadyPlanted) }

    #[error]
    const EPlotNotReady: vector<u8> = b"Crop is not ready to harvest yet";
    public fun plot_not_ready(condition: bool) { assert!(condition, EPlotNotReady) }

    #[error]
    const EPlotIsEmpty: vector<u8> = b"No crop planted on this plot";
    public fun plot_is_empty(condition: bool) { assert!(condition, EPlotIsEmpty) }

    #[error]
    const EMaxPlotsReached: vector<u8> = b"Maximum farm plots already owned";
    public fun max_plots_reached(condition: bool) { assert!(condition, EMaxPlotsReached) }

    #[error]
    const EInsufficientGold: vector<u8> = b"Not enough gold";
    public fun insufficient_gold(condition: bool) { assert!(condition, EInsufficientGold) }

    #[error]
    const EInsufficientSeeds: vector<u8> = b"Not enough seeds to plant";
    public fun insufficient_seeds(condition: bool) { assert!(condition, EInsufficientSeeds) }

    #[error]
    const EInsufficientCrops: vector<u8> = b"Not enough crops";
    public fun insufficient_crops(condition: bool) { assert!(condition, EInsufficientCrops) }

    #[error]
    const ECrowNoCharges: vector<u8> = b"No crow charges remaining";
    public fun crow_no_charges(condition: bool) { assert!(condition, ECrowNoCharges) }

    #[error]
    const ECrowTargetProtected: vector<u8> = b"Target farm is protected by a scarecrow";
    public fun crow_target_protected(condition: bool) { assert!(condition, ECrowTargetProtected) }

    #[error]
    const EInvalidCropType: vector<u8> = b"Invalid crop type";
    public fun invalid_crop_type(condition: bool) { assert!(condition, EInvalidCropType) }

    #[error]
    const ESeasonNotActive: vector<u8> = b"No active season";
    public fun season_not_active(condition: bool) { assert!(condition, ESeasonNotActive) }

    #[error]
    const ENotAdmin: vector<u8> = b"Caller is not the DApp admin";
    public fun not_admin(condition: bool) { assert!(condition, ENotAdmin) }

    #[error]
    const EHatchSlotBusy: vector<u8> = b"Already incubating an egg";
    public fun hatch_slot_busy(condition: bool) { assert!(condition, EHatchSlotBusy) }

    #[error]
    const ENoEggIncubating: vector<u8> = b"No egg is currently incubating";
    public fun no_egg_incubating(condition: bool) { assert!(condition, ENoEggIncubating) }

    #[error]
    const EEggNotReady: vector<u8> = b"Egg is not ready to hatch yet";
    public fun egg_not_ready(condition: bool) { assert!(condition, EEggNotReady) }

    #[error]
    const EPetNotFound: vector<u8> = b"Pet not found in your ranch";
    public fun pet_not_found(condition: bool) { assert!(condition, EPetNotFound) }

    #[error]
    const EPetSlotNotFound: vector<u8> = b"Pet slot does not exist";
    public fun pet_slot_not_found(condition: bool) { assert!(condition, EPetSlotNotFound) }

    #[error]
    const EPetSlotOccupied: vector<u8> = b"Pet slot already has a pet";
    public fun pet_slot_occupied(condition: bool) { assert!(condition, EPetSlotOccupied) }

    #[error]
    const EPetSlotEmpty: vector<u8> = b"No pet in that slot";
    public fun pet_slot_empty(condition: bool) { assert!(condition, EPetSlotEmpty) }

    #[error]
    const EMaxPetSlotsReached: vector<u8> = b"Maximum pet slots already owned";
    public fun max_pet_slots_reached(condition: bool) { assert!(condition, EMaxPetSlotsReached) }

    #[error]
    const EInsufficientEggs: vector<u8> = b"Not enough eggs of that type";
    public fun insufficient_eggs(condition: bool) { assert!(condition, EInsufficientEggs) }

    #[error]
    const EInvalidEggType: vector<u8> = b"Invalid egg type";
    public fun invalid_egg_type(condition: bool) { assert!(condition, EInvalidEggType) }

    #[error]
    const EInvalidPetSlot: vector<u8> = b"Invalid pet slot index";
    public fun invalid_pet_slot(condition: bool) { assert!(condition, EInvalidPetSlot) }
}
